### ISSUE TITLE
Screen Server Crash

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/MovingElevators#1]
`Minecraft v1.15.2`
`Forge v31.1.35`
`Moving Elevators v1.0`

After installing this mod on a server, the server crashes during the Load Registries stage.
[Crash Report](https://gist.github.com/WenXin20/6c20ecb5ac96e0d78ee5b212d0aee063)

**Comment by SuperMartijn642** [comment]
Found the issue and should be fixed in version 1.0.1 now

Thanks for the report!
