### ISSUE TITLE
[Bug] Falling through the elevator on 1.12

### ISSUE THREAD

**Issue by UtopianBublets** [SuperMartijn642/MovingElevators#100]
**Version Info**
- Minecraft Forge, 1.12.2
- Moving Elevators, 1.3.2

**Description of the Bug**
Falling through the elevator  i have tried different blocks i have also put a pictures of the mods im using @SuperMartijn642 

**Steps to Reproduce**
Followed your instructions but when i choose to go up the elevator goes up but drops me through it 

**Screenshots**
![Bottom](https://user-images.githubusercontent.com/100049160/154820576-8991a0ec-15e9-49ca-80d4-4fd524ca4605.png)
![top](https://user-images.githubusercontent.com/100049160/154820612-6590b699-87d3-4096-83df-a39e9529662a.png)
![image](https://user-images.githubusercontent.com/100049160/154820541-bf0802e0-6aad-400f-8fef-396b61047d12.png)

**Comment by SuperMartijn642** [comment]
This has already been fixed in Moving Elevators 1.3.2a for Minecraft 1.12.

**Comment by UtopianBublets** [comment]
Awesome 1.3.2a worked *Thumbs Up"
