### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Cal800** [SuperMartijn642/MovingElevators#103]
**Version Info** 
1.12.2
- Minecraft,
-  Java
- Moving Elevators, ...

**Are you using OptiFine?**: ...
NO
**Description of the Bug**
...
i have set up the elevators but when i click to send the elevator instaed of intinlizing the animation it just teleports up there isa no way to stay on the elevator while its moving so you either fall or just stay there
**Steps to Reproduce**
i watched countless videos and finally got it working just to find out you just tyeleport its abit annoyong.
i would appreciate advice

**Comment by SuperMartijn642** [comment]
What version of Moving Elevators are you using?

**Comment by Cal800** [comment]
i am using version 1.32

**Comment by Cal800** [comment]
also thank you for the quick reply

**Comment by SuperMartijn642** [comment]
> i am using version 1.32

I assume that's meant to be 1.3.2.
The issue has been fixed in version 1.3.3.

**Comment by Cal800** [comment]
thank you i switched version and it worked 

legend!
