### ISSUE TITLE
[Feature] Add russian translation

### ISSUE THREAD

**Issue by Den4enko** [SuperMartijn642/MovingElevators#105]
After the update, this mod messed up the translation. I fixed it.

Add this to mod.
[ru_ru.zip](https://github.com/SuperMartijn642/MovingElevators/files/8148285/ru_ru.zip)

**Comment by SuperMartijn642** [comment]
Thank you for the translations!

Could you submit the translations as a pull request? That way I can easily merge it and you will be credited with the changes.

To create a pull request:
Simply go to the existing translations file and click the edit button.
https://github.com/SuperMartijn642/MovingElevators/blob/1.18/src/main/resources/assets/movingelevators/lang/ru_ru.json
![image](https://user-images.githubusercontent.com/12382965/155899626-935a6188-08c3-420a-bbab-058e4c77f50e.png)
Then make your changes and press the 'Commit changes' button.
![image](https://user-images.githubusercontent.com/12382965/155899666-b0d100aa-aad1-4b22-8caf-193b45de0c0d.png)
Let me know if you have any questions.

**Comment by Den4enko** [comment]
Thank you!
