### ISSUE TITLE
[Bug] Dissapearing Blocks

### ISSUE THREAD

**Issue by VectorsWorld** [SuperMartijn642/MovingElevators#107]
**Version Info**
- Minecraft, 1.18.1
- Moving Elevators, ...

**Are you using OptiFine?**: yes

**Description of the Bug**
When the elevator is moving the blocks are disappearing 

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Please fill in all of the template

**Comment by SuperMartijn642** [comment]
I can't do anything here as I don't even know what version of Moving Elevators you're using.
