### ISSUE TITLE
[Bug] elevator rotates 45 degree using OptiFine

### ISSUE THREAD

**Issue by olaf231** [SuperMartijn642/MovingElevators#108]
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, Moving Elevators 1.3.4 for Minecraft 1.18

**Are you using OptiFine?**: yes

**Description of the Bug**
When using elevator the elevator rotate it self 45 degree to left, i tried using diffrent shaders. I used BSL and builders_QOL.
**Steps to Reproduce**
Just make elevator

**Screenshots**
(no, i'm not standing side ways)
![2022-03-10_22 04 30](https://user-images.githubusercontent.com/101364545/157754568-a9cd08b6-abb9-4598-9a3b-f0c290fe5afc.png)
This is the view before activating
![2022-03-10_22 04 31](https://user-images.githubusercontent.com/101364545/157754824-9799c5a3-481e-4901-9ca0-5984f1198b8d.png)

**Comment by SuperMartijn642** [comment]
Nothing I can do about this as OptiFine is closed source thus I can't know what it changes.
You'll have to report it to OptiFine.

**Comment by SirGalahad001** [comment]
Hi,
This looks like a similar issue that I have. Although my elevator is changing it's angle depending on the direction you look at it.
If so, then it has to do with shaders. If I turn shaders off, the elevator is moving correctly.
I already reported the issue to OptiFine: [#6636](https://github.com/sp614x/optifine/issues/6636).
