### ISSUE TITLE
[Feature] Chisel & Bits Support

### ISSUE THREAD

**Issue by hodo1962** [SuperMartijn642/MovingElevators#109]
It would be very nice to use Chisel & Bits with this mod to construct better
cabins.
At the moment elevators stop functioning when using bits from C&B ore
chiseled blocks.

**Comment by SuperMartijn642** [comment]
The elevator cabin currently can't contain tile entities. The Chisel & Bits' blocks have tile entities, just like a chests, furnace, or hopper, thus they won't work in the elevator cabin.

I will be adding the ability to use tile entities at some point. Thus, whenever I do, Chisel & Bits' blocks should also work.

**Comment by SuperMartijn642** [comment]
The elevators can now also move blocks with block entities.
