### ISSUE TITLE
[1.12.2] Sometimes, from some angles the front of the elevator controller renders white

### ISSUE THREAD

**Issue by fkrisi11** [SuperMartijn642/MovingElevators#11]
And here is a picture of this happening:
![elev](https://user-images.githubusercontent.com/26310365/79689433-1ab32300-8255-11ea-9155-9ff5041e3782.jpg)

**Comment by fkrisi11** [comment]
If I stand closer or to the left, it renders properly

**Comment by fkrisi11** [comment]
Note: This also happens if the controller has a skin on it

**Comment by SuperMartijn642** [comment]
I copied some lines from the 1.15 version which might fix it. I can't replicate it in my workspace so I think it's another block that gets rendered before the elevator controller that changes a default value.
I uploaded an alpha 1.2.4a version for 1.12, could you see if that fixes it?

**Comment by fkrisi11** [comment]
Yes. I will test it right away ^^

**Comment by fkrisi11** [comment]
![good](https://user-images.githubusercontent.com/26310365/79697558-c2dfe080-8283-11ea-8ff6-b0b59340626a.png)
![bad](https://user-images.githubusercontent.com/26310365/79697565-c83d2b00-8283-11ea-8316-ae1556b5bd92.jpg)

Still the same

**Comment by SuperMartijn642** [comment]
Thanks for the quick response.
Since I can see the display renders just fine, I changed the buttons to render the same way. Could you test 1.2.4b?

**Comment by fkrisi11** [comment]
My pleasure. I love this mod ^^
Let me see

**Comment by fkrisi11** [comment]
That was a perfect fix, @SuperMartijn642 .
1.2.4b rendering is perfect.

Thank you ^^

**Comment by SuperMartijn642** [comment]
Nice, I will push it to version 1.2.5.

Thanks for the report

**Comment by fkrisi11** [comment]
No problem. And thank you.
