### ISSUE TITLE
[Crash] 1.12.2 It crashes during launch

### ISSUE THREAD

**Issue by juckerspiel** [SuperMartijn642/MovingElevators#110]
**Version Info**
- Minecraft, ... 1.12.2
- Moving Elevators, ... 1.3.4

**Are you using OptiFine?**: ... Yes

**Steps to Reproduce**
... I don't know what ^this means. I added this mod along with other mods, and if I add this mod, it crashes during launch.
When I take it out from the file, it works again. I really want to put this mod in. How can I solve this?

**Crash report (~/logs/latest.log)**
... ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-03-20 22:57:55 YAKT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zzb001$beforeConstructingMods(Loader.java:1641)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SuperMartijn642** [comment]
Could you upload the entire log file, this is only a small part of it

**Comment by juckerspiel** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-03-20 22:57:55 YAKT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zzb001$beforeConstructingMods(Loader.java:1641)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1222273416 bytes (1165 MB) / 2086141952 bytes (1989 MB) up to 6413090816 bytes (6116 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6880m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 78 mods loaded, 78 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                       | Version                   | Source                                                    | Signature                                |
       |:----- |:------------------------ |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft                | 1.12.2                    | minecraft.jar                                             | None                                     |
       | L     | mcp                      | 9.42                      | minecraft.jar                                             | None                                     |
       | L     | FML                      | 8.0.99.99                 | forge-1.12.2-14.23.5.2859.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                    | 14.23.5.2859              | forge-1.12.2-14.23.5.2859.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | creativecoredummy        | 1.0.0                     | minecraft.jar                                             | None                                     |
       | L     | littletilescore          | 1.0.0                     | minecraft.jar                                             | None                                     |
       | L     | micdoodlecore            |                           | minecraft.jar                                             | None                                     |
       | L     | otgcore                  | 1.12.2-v9.4               | minecraft.jar                                             | None                                     |
       | L     | foamfixcore              | 7.7.4                     | minecraft.jar                                             | None                                     |
       | L     | creativecore             | 1.10.0                    | CreativeCore_v1.10.70_mc1.12.2.jar                        | None                                     |
       | L     | littletiles              | 1.5.0                     | LittleTiles_v1.5.57_mc1.12.2.jar                          | None                                     |
       | L     | alet                     | 1.0                       | A_Little_Extra_Tiles-1.0.23.jar                           | None                                     |
       | L     | jei                      | 4.16.1.301                | jei_1.12.2-4.16.1.301.jar                                 | None                                     |
       | L     | abyssalcraft             | 1.10.4                    | AbyssalCraft-1.12.2-1.10.4.jar                            | None                                     |
       | L     | aether_legacy            | 1.5.3.2                   | aether-1.12.2-v1.5.3.2.jar                                | None                                     |
       | L     | orbis-lib                | 0.2.0                     | orbis-lib-1.12.2-0.2.0+build411.jar                       | None                                     |
       | L     | aether                   | 0.3.0                     | aether_ii-1.12.2-0.3.0+build411-universal.jar             | None                                     |
       | L     | aoa3                     | 3.3.6                     | AoA3-3.3.6.jar                                            | None                                     |
       | L     | galacticraftcore         | 4.0.2.280                 | GalacticraftCore-1.12.2-4.0.2.280.jar                     | None                                     |
       | L     | armourers_workshop       | 1.12.2-0.51.0             | Armourers-Workshop-1.12.2-0.51.0.jar                      | None                                     |
       | L     | aroma1997core            | 2.0.0.2                   | Aroma1997Core-1.12.2-2.0.0.2.jar                          | None                                     |
       | L     | aroma1997sdimension      | 2.0.0.2                   | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar           | None                                     |
       | L     | baubles                  | 1.5.2                     | Baubles-1.12-1.5.2.jar                                    | None                                     |
       | L     | atum                     | 2.0.20                    | Atum-1.12.2-2.0.20.jar                                    | None                                     |
       | L     | badmobs                  | 1.1.40                    | BadMobs-1.12.2-1.1.40.jar                                 | None                                     |
       | L     | biomesoplenty            | 7.0.1.2445                | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar             | None                                     |
       | L     | blue_skies               | 1.1.3                     | blue_skies-1.12.2-v1.1.3.jar                              | None                                     |
       | L     | cavern                   | 2.3.1                     | Cavern_1.12.2-v2.3.1.jar                                  | None                                     |
       | L     | chiselsandbits           | 14.33                     | chiselsandbits-14.33.jar                                  | None                                     |
       | L     | cleanse                  | 1.12-1.0.1.1              | Cleanse-1.12-1.0.1.1.jar                                  | None                                     |
       | L     | cloudcontrol             | 1.0.0                     | cloudcontrol_v1.0.0formc1.12.2.jar                        | None                                     |
       | L     | controlling              | 3.0.10                    | Controlling-3.0.10.jar                                    | None                                     |
       | L     | creativeplus             | 1.0.2                     | CreativePlus MC1.12.2 v1.0.2.jar                          | None                                     |
       | L     | ctm                      | MC1.12.2-1.0.2.31         | CTM-MC1.12.2-1.0.2.31.jar                                 | None                                     |
       | L     | customnpcs               | 1.12                      | CustomNPCs_1.12.2-(05Jul20).jar                           | None                                     |
       | L     | dimdoors                 | 3.0.9-288                 | DimensionalDoors-3.0.9-288.jar                            | None                                     |
       | L     | effortlessbuilding       | 1.12.2-2.16               | effortlessbuilding-1.12.2-2.16.jar                        | None                                     |
       | L     | erebus                   | 1.0.32                    | Erebus-1.0.32.jar                                         | None                                     |
       | L     | galacticraftplanets      | 4.0.2.280                 | Galacticraft-Planets-1.12.2-4.0.2.280.jar                 | None                                     |
       | L     | mjrlegendslib            | 1.12.2-1.2.1              | MJRLegendsLib-1.12.2-1.2.1.jar                            | None                                     |
       | L     | extraplanets             | 1.12.2-0.7.4              | ExtraPlanets-1.12.2-0.7.4.jar                             | None                                     |
       | L     | foamfix                  | 0.10.14-1.12.2            | foamfix-0.10.14-1.12.2.jar                                | None                                     |
       | L     | glacidus                 | 1.2.1                     | Glacidus-1.12.2-v1.2.1.jar                                | None                                     |
       | L     | waila                    | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                               | None                                     |
       | L     | journey                  | 1.0.6.11                  | Journey-Into-The-Light-1.12.2-1.0.6.11.jar                | None                                     |
       | L     | journeymap               | 1.12.2-5.7.1              | journeymap-1.12.2-5.7.1.jar                               | None                                     |
       | L     | justenoughdimensions     | 1.6.0-dev.20200416.184714 | justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar | None                                     |
       | L     | jeid                     | 1.0.4-SNAPSHOT            | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar                     | None                                     |
       | L     | kathairis                | 1.12.2-1.6.0-beta         | Kathairis-1.12.2-1.6.0-beta.jar                           | None                                     |
       | L     | kirosblocks              | 1.2.1                     | kirosblocks-1.2.1.jar                                     | None                                     |
       | L     | landsoficaria            | beta-1.12.2-1.0.3         | landsoficaria-beta-1.12.2-1.0.3.jar                       | None                                     |
       | L     | littleframes             | 1.0.0                     | LittleFrames_v1.0.12_mc1.12.2.jar                         | None                                     |
       | L     | lottweaks                | 2.2.3a                    | LotTweaks-mc1.12.2-version-2.2.3a.jar                     | None                                     |
       | L     | mdxlib                   | 3.0.0.26                  | mdxlib-3.0.0.26.jar                                       | None                                     |
       | L     | mist                     | 1.2.5.3                   | MistyWorld-1.12.2-1.2.5.3.jar                             | None                                     |
       | L     | moreplayermodels         | 1.12.2                    | MorePlayerModels_1.12.2-(05Dec19).jar                     | None                                     |
       | L     | supermartijn642configlib | 1.0.9a                    | supermartijn642configlib-1.0.9a-mc1.12.jar                | None                                     |
       | L     | supermartijn642corelib   | 1.0.16a                   | supermartijn642corelib-1.0.16a-mc1.12.jar                 | None                                     |
       | L     | movingelevators          | 1.3.4                     | movingelevators-1.3.4-mc1.12.jar                          | None                                     |
       | L     | naturescompass           | 1.8.5                     | NaturesCompass-1.12.2-1.8.5.jar                           | None                                     |
       | L     | noaispawneggs            | 1.0.3                     | NoAISpawnEggs-1.12.2-1.0.3.jar                            | None                                     |
       | L     | patchouli                | 1.0-23.6                  | Patchouli-1.0-23.6.jar                                    | None                                     |
       | L     | tammodized               | 0.15.6                    | TamModized-1.12.2-0.15.6.jar                              | None                                     |
       | L     | tellme                   | 0.7.0-dev.20200919.184303 | tellme-1.12.2-0.7.0-dev.20200919.184303.jar               | None                                     |
       | L     | theabyss                 | 3.1.5                     | TheAbyss 3.5.0LV 1.12.2.jar                               | None                                     |
       | L     | theaurorian              | 1.12.2-Release            | theaurorian-1.12.2-release-may3021.jar                    | None                                     |
       | L     | thedalekmod              | (Update 64.1.0)           | thedalekmod-64.1.0.jar                                    | None                                     |
       | L     | tirphycraft              | 0.2                       | tirphycraft_B_1.12.2_1.0.jar                              | None                                     |
       | L     | tragicmc                 | 1.57.5258                 | TragicMC3-1.12.2-1.57.5258.jar                            | None                                     |
       | L     | twilightforest           | 3.11.1021                 | twilightforest-1.12.2-3.11.1021-universal.jar             | None                                     |
       | L     | ultra_amplified_mod      | 4.6.2                     | ultra_amplified_mod-1.12.2-4.6.2.jar                      | None                                     |
       | L     | vanillafix               | 1.0.10-150                | VanillaFix-1.0.10-150.jar                                 | None                                     |
       | L     | voidcraft                | 0.26.10                   | VoidCraft-1.12-0.26.10.jar                                | None                                     |
       | L     | waystones                | 4.1.0                     | Waystones_1.12.2-4.1.0.jar                                | None                                     |
       | L     | worldedit                | 6.1.10                    | worldedit-forge-mc1.12.2-6.1.10-dist.jar                  | None                                     |
       | L     | phosphor-lighting        | 1.12.2-0.2.6              | phosphor-1.12.2-0.2.6+build50.jar                         | None                                     |
       | L     | thebetweenlands          | 3.8.1                     | TheBetweenlands-3.8.1-universal.jar                       | None                                     |
       | L     | midnight                 | 0.3.5                     | themidnight-0.3.5.jar                                     | None                                     |
  Loaded coremods (and transformers): CCLoadingPlugin (cloudcontrol_v1.0.0formc1.12.2.jar)
                                        com.luwin.core.CCTransformer
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MistHookLoader (MistyWorld-1.12.2-1.2.5.3.jar)
                                        ru.liahim.mist.core.minecraft.PrimaryClassTransformer
                                      SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.16a-mc1.12.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      LittlePatchingLoader (LittleTiles_v1.5.57_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      FMLModule (mdxlib-3.0.0.26.jar)
                                        com.asx.mdx.AccessTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.29' Renderer: 'NVIDIA GeForce GTX 960M/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2859
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 497.29, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by SuperMartijn642** [comment]
It seems the crash is caused by VanillaFix. You'll have to report the issue to them.
