### ISSUE TITLE
[Question] Larger cabin size

### ISSUE THREAD

**Issue by sxcjnjnsdjhf** [SuperMartijn642/MovingElevators#112]
hello is there a way to make a biger cabnin than 7x7x7?
THx

**Comment by sxcjnjnsdjhf** [comment]
![Screen Shot 2022-03-21 at 15 53 14](https://user-images.githubusercontent.com/100861329/159275670-4c3b62e9-ae02-45d6-8b14-47c76032155f.png)

**Comment by SuperMartijn642** [comment]
You can change the maximum cabin size in Moving Elevators' config file

**Comment by sxcjnjnsdjhf** [comment]
> You can change the maximum cabin size in Moving Elevators' config file

wherse that i maybe dont see it becouse im on macos??

**Comment by SuperMartijn642** [comment]
It's in `/config/movingelevators-common.toml` (1.14+) or `/config/movingelevators-common.cfg` (1.12) in whatever folder you have set minecraft to run in.

**Comment by sxcjnjnsdjhf** [comment]
can i make it mor than 15?

**Comment by sxcjnjnsdjhf** [comment]
> It's in `/config/movingelevators-common.toml` (1.14+) or `/config/movingelevators-common.cfg` (1.12) in whatever folder you have set minecraft to run in.
can i make it mor than 15?

**Comment by SuperMartijn642** [comment]
No, 15x15x15 is already very large. Even larger will likely cause lag when the elevator cabin's blocks get broken/placed whenever the elevator stops or starts moving.

**Comment by sxcjnjnsdjhf** [comment]
ok thx
