### ISSUE TITLE
[Bug] the blocks became invisible when the elevator is going

### ISSUE THREAD

**Issue by FUTONASSA** [SuperMartijn642/MovingElevators#119]
**Version Info**
- Minecraft, 1.18.1
- Moving Elevators, ...

**Are you using OptiFine?**: yes

**Description of the Bug**
when i go whit the elevator it turn invisible

**Steps to Reproduce**
...

**Screenshots**
...
![2022-04-16_19 06 08](https://user-images.githubusercontent.com/103846932/163684687-9eb6b388-6817-4239-b568-bae7d955223a.png)

**Comment by SuperMartijn642** [comment]
What version of Moving Elevators are you using?

It is likely caused by OptiFine. Please confirm if the issue is present without OptiFine.

**Comment by FUTONASSA** [comment]
the problem is still even if i remove optifine

**Comment by FUTONASSA** [comment]
> 



> the problem is still even if i remove optifine

**Comment by SuperMartijn642** [comment]
What version of Moving Elevators and of my core library are you using?

**Comment by FUTONASSA** [comment]
movingelevators-1.3.6-mc1.18
supermartijn642corelib-1.0.16a-mc1.18

**Comment by SuperMartijn642** [comment]
This is an issue with my core library version 1.0.16a for 1.18, please update to 1.0.16b.

**Comment by FUTONASSA** [comment]
thanks, now it is fixed
