### ISSUE TITLE
[Question] How do i use redstone with an elevator to make it automatically go up/down floors?

### ISSUE THREAD

**Issue by Catomax262** [SuperMartijn642/MovingElevators#122]
**Question**
I have seen the creator use a button to go down his elevator with a button on the gif, but i can only make it call the elevator when there's a pulse. How?

**Comment by SuperMartijn642** [comment]
In the gif, I send a redstone signal to a remote elevator panel bound to the floor below.

**Comment by SuperMartijn642** [comment]
Closing due to no response.
