### ISSUE TITLE
[Minor Bug] Weird texture artifact when distancing from any elevator component

### ISSUE THREAD

**Issue by Desempregago** [SuperMartijn642/MovingElevators#123]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.3.6

**Are you using OptiFine?**: No.

[Video Proof](https://streamable.com/14h6u6)

**Comment by Desempregago** [comment]
Modlist:
![image](https://user-images.githubusercontent.com/14002834/165299780-40c44b77-251b-420b-bf19-c2724f465d7d.png)

**Comment by SuperMartijn642** [comment]
I cannot reproduce this issue with just Moving Elevators. It is likely caused by some other block getting into view when you walk a bit back and then changing some OpenGL state.
