### ISSUE TITLE
[Bug] Elevator platform disappear with a shader

### ISSUE THREAD

**Issue by oMiCid00** [SuperMartijn642/MovingElevators#126]
**Version Info**
- Minecraft 1.18.2, Forge 40.1.10
- movingelevators-1.3.7-forge-mc1.18.jar
- Shaders : ComplementaryShaders_v4.4

**Are you using OptiFine?**: yes, OptiFine_1.18.2_HD_U_H7.jar

**Description of the Bug**
the Elevator platform dispear when its moving and when i'm using my shaders.
When I set Parallax Occlusion Mapping on _OFF_, I managed to make it appears again but in a very weird position.
The position seems moving when my character is moving

**Steps to Reproduce**
Using Shaders : ComplementaryShaders_v4.4

**Screenshots**
![2022-05-22_01 58 05](https://user-images.githubusercontent.com/39798805/169672758-98183805-e1be-4812-8210-708c192f18e8.png)
![2022-05-22_01 58 23](https://user-images.githubusercontent.com/39798805/169672759-23794a9f-484c-481e-84cc-517576f0536c.png)

**Comment by SuperMartijn642** [comment]
Nothing I can do about this as OptiFine is closed source, thus I can't know what it changes. Trying to randomly change stuff until it works would just waste my time and potentially break with other mods.
The issue has been reported to OptiFine https://github.com/sp614x/optifine/issues/6636, but I doubt that will lead to much.

For now, I can only say don't use OptiFine.

**Comment by SDUBZ** [comment]
i would say try with oculus which is a shader loader and i have seen little issues with that in terms of modded compat
