### ISSUE TITLE
[Crash] Remote elevator controllers causing weird redstone behavior and crashes

### ISSUE THREAD

**Issue by Knopfi02** [SuperMartijn642/MovingElevators#127]
**Version Info**
- Minecraft, 1,18,2
- Moving Elevators, 1.3.7

**Are you using OptiFine?**:  No

**Steps to Reproduce**
2 elevator controllers and for each level a remote elevator controller with a button on it.
Sometimes the chunk that the elevator is in, starts to not update blocks (redstone not working, buttons stay pressed in, water won't flow and so on) and after restarting the server the lighting in the chunk is messed up. Everything is dark and is fixed by updating the lighting (placing a light source in the chunk)
Block updating glitch is fixed by restarting the server, however it returns after an undetermined amount of time.

**Crash report (~/logs/latest.log)**
[crash-2022-05-27_13.16.46-server.txt](https://github.com/SuperMartijn642/MovingElevators/files/8786721/crash-2022-05-27_13.16.46-server.txt)

**Other Mods used**
- Chipped, Cooking for Blockheads, FastLeafDecay, Gravestone mod, Immersive Engineering, Mawcaw's Doors and Bridges, More Minecarts, MrCrayfish's Furniture Mod, Pam's Harvestcraft 2, Storage Drawers, Torchmaster, Ultimate Cat Mod
plus some required library mods

**Comment by SuperMartijn642** [comment]
Whoops sorry, forgot to respond to the issue here. It should be now fixed in Moving Elevators 1.3.9.

Thank you for reporting the issue!
