### ISSUE TITLE
[Bug] Duplicating Pistons

### ISSUE THREAD

**Issue by ChronicSquid13** [SuperMartijn642/MovingElevators#128]
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, 1.3.7

**Are you using OptiFine?**: No

**Description of the Bug**
having an extended piston, either sticky or default causes the piston to drop an entity of itself.

**Steps to Reproduce**

1. Place an activated piston (Sticky or Default)
2. Move Elevator

**Screenshots**

[**GIF of Issue**](https://i.mikemo.xyz/i/9Lp51lOnvj.gif)

![2022-05-28_14 08 50](https://user-images.githubusercontent.com/8313516/170837819-33e14907-df41-4c4c-b51f-aa2c7ac5f83b.png)

**Comment by SuperMartijn642** [comment]
This has been fixed now in Moving Elevators version 1.4.9.
Thank you for reporting the issue!
