### ISSUE TITLE
[Bug] Clicking the edge of elevator display causes an error output

### ISSUE THREAD

**Issue by Clpsplug** [SuperMartijn642/MovingElevators#129]
**Version Info**
- Minecraft 1.17.1 MultiMC5/Forge
- Moving Elevators 1.3.7
- ConfigLib 1.0.9
- CoreLib 1.0.18
All Mods are obtained through CurseForge. No other block-adding mods are installed.

**Are you using OptiFine?**: YES

**Description of the Bug**
Right-clicking the very edge of the Elevator Displays causes the right-clicking routine of this mod to flip out and output the following log.  
The game does *not* crash because of this issue.

https://gist.github.com/Clpsplug/9e1b4aa6eefb1b604f0b614fe1a0f123

NOTE: Clicking the surface of the floor selector does not cause an error, but clicking the *edge of the surface of the selector* does.

**Steps to Reproduce**
1. Create an elevator. Make sure you include an elevator display in the design.
2. Call the elevator to the floor you are on.
3. Click the *very edge* of the elevator display.
4. Observe the log.

**Screenshots**

**Click for the full FPS footage** or visit https://gyazo.com/2bc440b5b9a403589c689ee0cfeb52f6  
Notice that the second time I click the elevator display, I aim at the very edge of the display, which will cause the error output in the log shown on the left.

[![Image from Gyazo](https://i.gyazo.com/2bc440b5b9a403589c689ee0cfeb52f6.gif)](https://gyazo.com/2bc440b5b9a403589c689ee0cfeb52f6)

**Comment by SuperMartijn642** [comment]
I fixed the issue now in Moving Elevators 1.3.9.
Thank you for reporting the issue!
