### ISSUE TITLE
[1.12.2] Invalid texture crash

### ISSUE THREAD

**Issue by fkrisi11** [SuperMartijn642/MovingElevators#13]
Crashlog: https://pastebin.com/bMLHZ6Am

I tried to disguise an elevator with a haybale, which caused this crash to happen.
It says it is a client crash.
When it happens, the whole screen goes black, and then the client crashes. The block stays in the world, so it crashes the client each time it loads.

**Comment by fkrisi11** [comment]
No matter if you disguise the controller or the display, it crashes you in both cases

**Comment by SuperMartijn642** [comment]
Found the issue, I fixed it in 1.2.7.
Thanks for the report!

**Comment by fkrisi11** [comment]
Thank you ^^

What caused the issue btw, @SuperMartijn642 ?
