### ISSUE TITLE
[Question] Why does the elevator only workt to LVL 0

### ISSUE THREAD

**Issue by TLF2040SL** [SuperMartijn642/MovingElevators#132]
**Question**
...
Hey there I have a Question 
why does the elevators only work to LVL 0 when in Minecraft 1.18 and following the world goes
to lvl -64 ?

**Comment by SuperMartijn642** [comment]
What do you mean by 'only works to level 0'? What version of Moving Elevators are you using?

**Comment by TLF2040SL** [comment]
hello 
we are using the newest version "movingelevators-1.3.7-forge-mc1.18.jar"
i mean i tried to make a long elevator from y-coordinate 72 to y: -50 but it doesn´t work und y=0 
it connects with the controller blocks above but i cant call the elevator nor can send the elevator to this floors

**Comment by SuperMartijn642** [comment]
Are you sure there are no blocks in the way of the cabin at the bottom controller?

**Comment by SuperMartijn642** [comment]
Closing due to no response.
