### ISSUE TITLE
[Crash] ... Error Loading Mods (requires supermartijn642...) 

### ISSUE THREAD

**Issue by PpasCheddar** [SuperMartijn642/MovingElevators#133]
1.19
- Minecraft, java
- Moving Elevators, ...

**Are you using OptiFine?**: yes

This is what appears when trying to open my version 1.19 of Minecraft. Which has other mods aside from Moving Elevators. It also has Optifine and Forge installed. I don't know what could be the error or the installable file to make this version of Moving Elevators work in my game. I hope a prompt response and solution for this, I really like this mod and I would like to continue applying it in my worlds.

**Steps to reproduce:**
Open Launcher
I select PLAY my version 1.19 with Forge and other mods installed.
My game loads and before seeing the main menu this message appears

**Crash report (~/logs/latest.log)**
... 
![WhatsApp Image 2022-07-03 at 3 38 17 PM](https://user-images.githubusercontent.com/108628866/177052925-4c9f1ccb-f920-456c-ac05-7302d42a1d67.jpeg)

These are the files that show when i press **Open latest.org** and **Open crash-2022...**

[crash-2022-07-03_15.30.57-fml.txt](https://github.com/SuperMartijn642/MovingElevators/files/9035336/crash-2022-07-03_15.30.57-fml.txt)
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/9035337/latest.log)

**Comment by Reyzerbit** [comment]
Bro it literally tells you that you are missing dependency mods... can you read which ones?

**Comment by PpasCheddar** [comment]
> Bro it literally tells you that you are missing dependency mods... can you read which ones?

And where the hell are those

**Comment by SuperMartijn642** [comment]
Just click on the file you want to use.
![image](https://user-images.githubusercontent.com/12382965/177054572-2df0a38e-fcb1-40d3-b303-1ee4170d89f7.png)

**Comment by PpasCheddar** [comment]
Thank you, i solved it. I recently start to play Minecraft again so i forget how simple things like this works.
