### ISSUE TITLE
[Crash] Game crashes at start on any newer versions of Forge [1.19]

### ISSUE THREAD

**Issue by jonasCCa** [SuperMartijn642/MovingElevators#134]
**Version Info**
- Minecraft, 1.19
- Forge, 41.0.38
- Moving Elevators, 1.3.7

**Are you using OptiFine?**: No

**Steps to Reproduce**
Load game with nothing but Forge this mod, it crashes at the first loading screen.
This is probably due to the forge version, if you update the mod to Forge 41.0.30 or higher it should work properly. Any lower Forge versions are uncompatible due to some liquid API or something like that.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/9041423/latest.log)

**Comment by SuperMartijn642** [comment]
Moving Elevators requires my core and config libraries. There is currently and issue in Forge where it just crashes instead of showing the messages about the dependencies.

**Comment by jonasCCa** [comment]
> Moving Elevators requires my core and config libraries. There is currently and issue in Forge where it just crashes instead of showing the messages about the dependencies.

Oh... my bad. I should've seen the relations page on Curseforge, sorry about that. It's working properly now.
I assumed it was the problem I described because I saw it on some other mods during this initial 1.19 Forge update.

Anyway, thanks for the quick reply!
