### ISSUE TITLE
[Crash] ... I was making an elevator and then I broke the elevator controller, I then replaced it for a elevator remote panel, here's what happened 1. The block does not render. 2. The screen says not responding in the corner. 3. The world crashes followed by the game crashing. Here's the crash exit code: The game crashed whilst rendering block entity. Exit code: -1. P.S. I replicated the crash and it stayed on the not responding stage and the said OpenJDK was not responding the other things are the same though. Also Im using the right versions for the dependencies.

### ISSUE THREAD

**Issue by EXPERTmodder078** [SuperMartijn642/MovingElevators#137]
**Version Info**
- Minecraft, ...1.18.2 Forge
- Moving Elevators, ... for 1.18.2 Forge

**Are you using OptiFine?**: ...No I'm not using Optifine because I was also using the create mod and optifine is not compatible with it.

**Steps to Reproduce**
...Put the Controller 1 block above the ground then break it and replace it with the remote panel. Also make sure you are using my versions.

**Crash report (~/logs/latest.log)**
... I could not find the logs/latest.log :(

**Comment by SuperMartijn642** [comment]
For next time, please put the description of the problem in the issue instead of in the title.

I fixed the crash now in Moving Elevators 1.3.9.
Thank you for reporting the issue!
