### ISSUE TITLE
Elevator not working?

### ISSUE THREAD

**Issue by shellorien** [SuperMartijn642/MovingElevators#138]
I have tried remodeling my elevator multiple times but no matter what, except once, I can't call or move the elevator at all. Is there a special trick to modeling the elevator to make it work? It is a 3-story elevator. I've attached photos of the elevator I created just in case anyone could spot what I did wrong :)

![2022-07-30_19 05 22](https://user-images.githubusercontent.com/110315895/182006677-1b1ab22d-f8fb-41fe-aa42-34c4daa2de71.png)
![2022-07-30_19 05 27](https://user-images.githubusercontent.com/110315895/182006678-8c8b46dc-e1f8-4649-a89e-227cbb6c2258.png)
![2022-07-30_19 05 50](https://user-images.githubusercontent.com/110315895/182006679-3b7dd59c-4227-40c7-90a1-77cbf66987aa.png)
![2022-07-30_19 05 53](https://user-images.githubusercontent.com/110315895/182006681-35fb844d-fa07-4956-80b9-fbb4739fc821.png)
![2022-07-30_19 04 21](https://user-images.githubusercontent.com/110315895/182006682-cd184209-2361-4c63-83c8-e7664dfff3df.png)
![2022-07-30_19 04 58](https://user-images.githubusercontent.com/110315895/182006683-6ea85893-bd18-4e76-8d19-9b6a4380208c.png)

**Comment by SuperMartijn642** [comment]
Looks like it should work to me. The only thing I can think of is that one of those lights or that bench has a block entity, since the elevator doesn't support moving block entities.

**Comment by Valafore** [comment]
Hi, on this one, you should try with a height of 6 instead of 7. I hasn't been able to make it works with 7 on 1.19.2 + forge. 

Not sure if it is planned, but I cannot either use the elevator if I have an enchantment table in the lift. Not a big deal, I am still addicted to this mod, easy to use and well done!
