### ISSUE TITLE
[Crash] ...Problem With crackers wither storm mod

### ISSUE THREAD

**Issue by MechtroYT** [SuperMartijn642/MovingElevators#141]
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators,1.3.9

**Are you using OptiFine?**: ...
No
**Steps to Reproduce**
Just Happends

**Crash report (~/logs/latest.log)**
https://pastebin.com/A9WryJnR

Ive Already Reported this to the crackers wither storm mod issues

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.11.

Thank you for reporting the issue!
