### ISSUE TITLE
[Bug] Open to lan server elevator causing player disconnection 

### ISSUE THREAD

**Issue by luizfranzon** [SuperMartijn642/MovingElevators#142]
**Version Info**
- 1.19.2-forge-43.1.24
- movingelevators-1.3.9-forge-mc1.19

**Self made modpack** : https://www.technicpack.net/modpack/bunker-doido.1939954

**Are you using OptiFine?**: No

**Description of the Bug**
While playing in a open to lan server, when the elevator is used and get to the floor, my friend get disconnected with an error message:

*Internal Exception: java.lang.IllegalStateExpection: Received an unregistered packet with index '4352'!*
sometimes the "4352" value is "128000"

**Screenshots**

![errorMessage](https://user-images.githubusercontent.com/88747741/189512179-9a7528a5-57d3-4d5f-b7c2-a2f8a4b18e40.png)

### Mods list
![modsList](https://user-images.githubusercontent.com/88747741/189512237-e697dda3-c7f0-4ff8-8f04-0d47194127dc.png)

**Comment by SuperMartijn642** [comment]
This should be fixed by updating to version 1.1.0 of my core library.

Thank you for reporting the issue!
