### ISSUE TITLE
[Question] How do i make this elevator functional?

### ISSUE THREAD

**Issue by Catomax262** [SuperMartijn642/MovingElevators#143]
The elevator is the 5x5 box of whitish beams,
How do i make it so it can move without it being naked or making a hole on it? (I want it hidden, i want to use remote panels) I have no experience with remote panels and some tutorials are outdated.

![2022-11-03_00 50 14](https://user-images.githubusercontent.com/80112576/199655899-d001649b-3ff5-4b63-b9c4-fc6e4867a074.png)
![2022-11-03_00 50 21](https://user-images.githubusercontent.com/80112576/199655901-d56eebe6-5b75-40d2-9c3f-3d0e1f3d5a7a.png)
![2022-11-03_00 55 25](https://user-images.githubusercontent.com/80112576/199655915-ce9604b3-830a-4e93-b8e6-c69a0d6e858d.png)
![2022-11-03_00 50 42](https://user-images.githubusercontent.com/80112576/199655924-ab189b93-36fb-44e9-8e1e-e1e9ce6849fd.png)

**Comment by SuperMartijn642** [comment]
The elevator cannot have any block entities in it. My guess would be that one of those blocks has a block entity.
