### ISSUE TITLE
Elevator buttons disapearing depending on the angle of the camera

### ISSUE THREAD

**Issue by RealRandomes** [SuperMartijn642/MovingElevators#145]
So, if im looking directly at the buttons they appear as normal, but if i look away just a little bit they disapear, it's not a big deal but it's a bit uggly to look at, im using other mods but it's been weeks since im using them with this mod and only today this started happening.
My Minecraft version is 1.12.2

**Comment by SuperMartijn642** [comment]
Please fill in the issue template. I don't even know which version of Moving Elevators you're using.

**Comment by RealRandomes** [comment]
Sorry i don't know how to do that, but my version was the most recent 1.12.2 version at the time

**Comment by SuperMartijn642** [comment]
Just click the 'Bug report' button after you click new issue.
![image](https://user-images.githubusercontent.com/12382965/210188260-d32f8d7a-edef-450b-992d-e7d42af8c1e0.png)
