### ISSUE TITLE
[Crash] Failure message: Moving Elevators (movingelevators) has failed to load correctly 		org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by UrbanSide** [SuperMartijn642/MovingElevators#147]
**Version Info**
- Minecraft, 1.16.5
- Moving Elevators, 1.3.9

**Are you using OptiFine?**: No

**Steps to Reproduce**
Start game

**Crash report (~/logs/latest.log)**
https://mclo.gs/44N77u0

**Comment by SuperMartijn642** [comment]
You are using quite a lot of mods. Could you narrow down the mods needed to reproduce the issue?

Also not sure what the actual error is. It says Moving Elevators failed to load, but the error it shows is from a mixin from RandomPatches 🤔
