### ISSUE TITLE
[1.12.2] Not all dyes are correct maybe

### ISSUE THREAD

**Issue by fkrisi11** [SuperMartijn642/MovingElevators#15]
This happens with light gray dye:

![light gray](https://user-images.githubusercontent.com/26310365/80007220-425cf200-84c6-11ea-9ebd-05d5e2883861.png)

**Comment by fkrisi11** [comment]
Also.. is there a way to get back the original color for the floor?

**Comment by SuperMartijn642** [comment]
Is it only light gray?
The gray dye corresponds to the default color of the buttons.

**Comment by fkrisi11** [comment]
I'll test it in a moment

**Comment by fkrisi11** [comment]
Yes it is only light gray dye. Everything else is just fine.

**Comment by SuperMartijn642** [comment]
Yeah turns out the color for light gray dye is actually called silver and not light_gray, should be fixed in the next version.

**Comment by fkrisi11** [comment]
Thank you ^^
