### ISSUE TITLE
[Bug] Phasing through elevator as it goes up

### ISSUE THREAD

**Issue by Kowantify** [SuperMartijn642/MovingElevators#152]
**Version Info**
- Minecraft 1.19.2
- Moving Elevators 1.3.11a

**Are you using OptiFine? No, I'm using Rubidium

**Description of the Bug**
Whenever going down on the elevator I don't have issues, but going up I phase through the floor every time

**Steps to Reproduce**
Place an elevator, go up a floor, immediately phase through the floor, even on lowest blocks per tick setting

**Screenshots**

![2023-01-28_13 44 32](https://user-images.githubusercontent.com/35680697/215287760-61cdc1c8-64fc-42ad-9a63-cc9d7e61ccf7.png)
![2023-01-28_13 44 33](https://user-images.githubusercontent.com/35680697/215287762-ea8d5453-60f4-4313-9f06-34dea431b03a.png)
![2023-01-28_13 44 34](https://user-images.githubusercontent.com/35680697/215287767-0f290f1a-a67f-4dca-851d-5657c08b5f18.png)
![2023-01-28_13 44 35](https://user-images.githubusercontent.com/35680697/215287768-9c5ea26b-f3ce-4115-afa3-a1472d8e05be.png)
![2023-01-28_13 44 35_2](https://user-images.githubusercontent.com/35680697/215287771-d87c2fb2-bee6-4c95-bd7e-ffee970b4d96.png)
![2023-01-28_13 44 37](https://user-images.githubusercontent.com/35680697/215287772-2a146023-3a5a-492a-a779-84b8f1927452.png)
![2023-01-28_13 44 38](https://user-images.githubusercontent.com/35680697/215287774-b428cb6a-fb6a-44b9-97b5-f30cac9b3878.png)
![2023-01-28_13 44 39](https://user-images.githubusercontent.com/35680697/215287779-316af2ac-d2ce-48fc-9180-dab01d207c81.png)
![2023-01-28_13 44 39_2](https://user-images.githubusercontent.com/35680697/215287780-34014d64-aaca-4a3a-8900-404b7259949d.png)

**Comment by Kowantify** [comment]
This is happening in a quite large modpack, I'm not entirely sure what mod I have that is messing with moving entity's and so forth, but it definitely is messing with the mod, as the mod works fine with rubidium as tested

**Comment by Kowantify** [comment]
but when I go down the elevator it isn't smooth at all, my character stutters essentially, but when I test it by itself with some basic mods it's completely fine, is there a know mod that isn't compatible?>

**Comment by SuperMartijn642** [comment]
What you're describing sounds a known issue with OptiFine. Are you sure you are not using OptiFine? As far as I know Rubidium just has performance optimizations and what you have in those screenshots looks like shaders.

If it's not OptiFine, you'll have to do some investigating to find which other mod is causing the issue.

**Comment by Kowantify** [comment]
100% not optifine, I've been doing modpacks for a very very long time, Optifine is trash, I've literally removed half my mods, it worked, removed the other half, it worked, I'm beyond confused, but I think it's a combo of mods that causes it, usually the motion of the elevator moving is very smooth, but it isn't anymore, What type of mod would mess with the elevator? I'll attach my mods I'm using, I tried removing 20 mods at a time to test but this is incredibly tedious and difficult to narrow down

What your seeing is "oculus" but it works just fine without the modpack, when it is just oculus and rubidium

**Comment by Kowantify** [comment]
This is the modpack list and the links to the curseforge pages in the modpack, I've also tested like I stated by removing half, tested, it worked, removed the other half, tested, it worked, all together, doesn't work, I'm beyond confused on what is could possibly be, hopefully this modlist will have somthing stick out as messing with moving tile entities

["To the Bat Poles!" (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/to-the-bat-poles)
[Ad Astra! (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Additional Enchanted Miner (by Kotori316)](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner)
[Advanced Chimneys (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Aquaculture 2 (by Shadowclaimer)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Awesome Dungeon - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-forge)
[Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)
[Awesome Dungeon Ocean edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-forge)
[Awesome Dungeon The End edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-the-end-forge)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Better Animal Models (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/better-animal-models)
[Better Animations Collection (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-animations-collection)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[BlockUI (by H3lay)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Borderless Window (by SgtSalocin)](https://www.curseforge.com/minecraft/mc-mods/borderless)
[Born in Chaos (by mongoose_artist)](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Camera Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/camera-mod)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[CleanCut (by Rongmario)](https://www.curseforge.com/minecraft/mc-mods/cleancut)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Construction Wand (by ThetaDev)](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
[CorgiLib (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/corgilib)
[CoroUtil (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/coroutil)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[CraftPresence (by CDAGaming_)](https://www.curseforge.com/minecraft/mc-mods/craftpresence)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Decoration and Furniture (Forge) (by Skart2007)](https://www.curseforge.com/minecraft/mc-mods/decoration-and-furniture)
[Diagonal Fences (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[Domestication Innovation (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/domestication-innovation)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Dynamic Surroundings Resurrected (by theNyfaria)](https://www.curseforge.com/minecraft/mc-mods/dynamic-surrounding-resurrected)
[Easy Anvils (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
[EnhancedVisuals (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[Entity Culling Fabric/Forge (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Fish of Thieves (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Global XP (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/global-xp)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Grappling Hook Mod (by yyonne)](https://www.curseforge.com/minecraft/mc-mods/grappling-hook-mod)
[Hammer Lib (by Zeitheron)](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
[Horse Expert (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/horse-expert)
[Hourglass (by DuckyCrayfish)](https://www.curseforge.com/minecraft/mc-mods/hourglass)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Incendium (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/incendium)
[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[inzhefop's Core (by inzhefop)](https://www.curseforge.com/minecraft/mc-mods/inzhefop-core)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Iron Furnaces [FORGE] (by XenoMustache)](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Large Fluid Tank (by Kotori316)](https://www.curseforge.com/minecraft/mc-mods/largefluidtank)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Lucky TNT Lib (by Fleshcrafter_)](https://www.curseforge.com/minecraft/mc-mods/lucky-tnt-lib)
[Lucky TNT Mod (Too Much TNT) (by Fleshcrafter_)](https://www.curseforge.com/minecraft/mc-mods/luckytnt)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Macaw's Bridges - Biome O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Macaw's Fences - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-biomes-o-plenty)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Macaw's Furnitures - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-biomes-o-plenty)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Macaw's Roofs - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-biomes-o-plenty)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Magnesium/Rubidium Dynamic Lights (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[MCA Reborn [Fabric/Forge] (by jahx_senpoopie)](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)
[McJtyLib (by McJty)](https://www.curseforge.com/minecraft/mc-mods/mcjtylib)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Miner's Helmet (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/miners-helmet)
[MineTraps (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/minetraps)
[Mob Grinding Utils (by vadis365)](https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Moving Elevators (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/moving-elevators)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[MT: ClaySoldiers2 [Forge] (by LazTheArtist)](https://www.curseforge.com/minecraft/mc-mods/mt-claysoldiers2-forge)
[Multi Mine (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/multi-mine)
[Multi-Piston (by H3lay)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[MultiBeds (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/multibeds)
[MultiCoreLib (by LazTheArtist)](https://www.curseforge.com/minecraft/mc-mods/multicorelib)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[Nosiphus Furniture Mod (by Nosiphus)](https://www.curseforge.com/minecraft/mc-mods/nosiphus-furniture-mod)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Nullscape (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/nullscape)
[Nyf's Spiders (by theNyfaria)](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Packing Tape (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/packing-tape)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[Paladin's Furniture (by UnlikePaladin)](https://www.curseforge.com/minecraft/mc-mods/paladins-furniture)
[Passthrough Signs (by Girafi)](https://www.curseforge.com/minecraft/mc-mods/passthrough-signs)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Pipez (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/pipez)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Powah! (Rearchitected) (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected)
[Puzzles Lib (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Rubidium Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
[Rubik's Cube (by 7klima7)](https://www.curseforge.com/minecraft/mc-mods/rubiks-cube-mod)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Scalable Cat's Force (by Kotori316)](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force)
[SeasonHUD (by IanAnderson)](https://www.curseforge.com/minecraft/mc-mods/seasonhud)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[ShetiPhianCore (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore)
[Silent Gear (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-gear)
[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
[Silent's Gems (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silents-gems)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Simply Backpacks (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-backpacks)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Solar Flux Reborn (by Zeitheron)](https://www.curseforge.com/minecraft/mc-mods/solar-flux-reborn)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Statues (by ShyNieke)](https://www.curseforge.com/minecraft/mc-mods/statues)
[Storage Labels (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/labels)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Structurize (by H3lay)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[TexTrue's Rubidium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options)
[Tom's Simple Storage Mod (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage)
[Tool Stats (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tool-stats)
[Tough As Nails (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[U Team Core (by HyCraftHD)](https://www.curseforge.com/minecraft/mc-mods/u-team-core)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Whisperwoods (by itsmeowdev)](https://www.curseforge.com/minecraft/mc-mods/whisperwoods)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[Zombie Awareness (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/zombie-awareness)

**Comment by SuperMartijn642** [comment]
Moving Elevators relies on handling player movement for the elevator at the end of each tick, so most likely it would be a mod that messes with player movement in some way.
The only mods that stand out to me from that are Canary and Better Animation Collection. Could be any of them though, just those two caught my attention.
If it's not one of those, I can probably look into it tomorrow.

**Comment by KowalskiXCIX** [comment]
I will test both mods now!

**Comment by KowalskiXCIX** [comment]
YOU WERE RIGHT, It is one of those mods! I will narrow it down now

**Comment by KowalskiXCIX** [comment]
Player Animations Collection seems to be the cause of the issues

**Comment by KowalskiXCIX** [comment]
Both of them are causing the issue it seems?

**Comment by Kowantify** [comment]
I removed all mods.. Issue is persising, with ONLY moving elevators installed

**Comment by Kowantify** [comment]
Forge Version, 43.2.4, Moving Elevators 1.3.11a, SMConfigLib: 1.1.6b, SMCoreLIb: 1.1.1a
1.19.2

No other mods installed elevator stutters, player falls through as elevator goes up

**Comment by Kowantify** [comment]
https://user-images.githubusercontent.com/35680697/215293424-53d03030-ffb2-4344-a6e3-2b8d92932324.mov

Ignore the incredibly low quality, had to edit it via davinci resolve to meet the 10MB cap for file uploads on github

This is with the mod only install, brand new world, all new testing, most recent forge version, and this happens

**Comment by Kowantify** [comment]
Forge version 43.2.0, Works 
Forge version 43.2.1, Works 
Forge Version 43.2.2, Works
Forge Version 43.2.3, Works
Forge Version 43.2.4, Doesn't Work

That's the problem, it is just the most recent version of forge causing an issue

**Comment by SuperMartijn642** [comment]
Yup that seems to be it. Forge changed `LevelTickEvent` to also be fired on the client-side in 43.2.4.
Moving Elevators used `LevelTickEvent` server-side and `ClientTickEvent` client-side to handle the elevator movement. Since `LevelTickEvent` is now also fired client-side, the elevator's movement handling got called twice every tick leading to the issues you were experiencing.
A one line check does the trick for fixing it in 9fd0203118c38fad24cb769481e8de148be5b76e.

Should be fixed now in version 1.3.11b of Moving Elevators for 1.18, 1.19.2, and 1.19.3.
Thanks a lot for the help and reporting the issue!

**Comment by Kowantify** [comment]
Thank you so much for looking into this and fixing it so fast!
