### ISSUE TITLE
Version Fabric 1.19.2.

### ISSUE THREAD

**Issue by manu1978** [SuperMartijn642/MovingElevators#158]
Hello, I loved your mods when I was on Forge, do you plan to make a Fabric 1.19.2 compatible version?

**Comment by SuperMartijn642** [comment]
Nope

**Comment by wackoamd1** [comment]
martijn rather updates ancient forge versions like 1.16.5 then make a fabric 1.19.2 version Oo

**Comment by SuperMartijn642** [comment]
> martijn rather updates ancient forge versions like 1.16.5 then make a fabric 1.19.2 version Oo

Rather plays on ancient 1.19 subversions then update to 1.19.4.
