### ISSUE TITLE
[Crash] Fabric version crashes on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [SuperMartijn642/MovingElevators#159]
**Version Info**
- Minecraft, 1.19.4
- Moving Elevators, 1.3.12

**Are you using OptiFine?**: no

**Steps to Reproduce**
Simply install the mod and its dependencies, then run the game.

**Crash report (~/logs/latest.log)**
https://gist.github.com/SplendidAlakey/a38d50aa38439475e0ab1797be3fc268

**Comment by SuperMartijn642** [comment]
I fixed it now in Moving Elevators version 1.3.12a.

Thank you for reporting the issue!
