### ISSUE TITLE
[Crash] Placing Elevator Controller crashes game

### ISSUE THREAD

**Issue by RedaunAmarien** [SuperMartijn642/MovingElevators#160]
**Version Info**
- Minecraft, 1.19.4
- Forge, 45.0.43
- Moving Elevators, 1.3.11b
(I'm not sure it's supposed to be available for 1.19.4 Forge but it _is_ listed as compatible in CurseForge. That could be the entire problem right there.)

**Are you using OptiFine?**:
No, reproduced with only Forge and ME's dependencies installed.

**Steps to Reproduce**
Create new world, obtain an elevator controller block, and place it down. Game immediately crashes. World becomes un-openable until removing the ME mod.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/11256213/latest.log)

**Comment by SuperMartijn642** [comment]
Most of the changes in 1.19.4 are obscured by my core library, so I haven't tested the individual mods. Most of the mods work fine, but I guess Moving Elevators did need some changes.
It should work now with the dedicated file for 1.19.4.

Thank you for reporting the issue!
