### ISSUE TITLE
[Crash] Crash with Rubidium

### ISSUE THREAD

**Issue by MCEventHorizon** [SuperMartijn642/MovingElevators#161]
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, 1.4.0

**Are you using OptiFine?**: no

**Steps to Reproduce**
update from 1.3.12 to 1.4.0

**Crash report (~/logs/latest.log)**

[crash-2023-04-26_10.01.01-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/11330524/crash-2023-04-26_10.01.01-client.txt)

**Comment by SuperMartijn642** [comment]
Seems to be a conflict with Rubidium.

**Comment by DarthCaesium** [comment]
I seem to have the same issue in 1.19.2 with Rubidium 0.6.2a. Forge version is 43.2.11.
