### ISSUE TITLE
[Crash] it keeps crashing

### ISSUE THREAD

**Issue by jorgestudios** [SuperMartijn642/MovingElevators#162]
**Version Info**
- Minecraft, 1.12.2 14.23.5.2860 
- Moving Elevators, movingelevators-1.4.1-forge-mc1.12.jar

**Are you using OptiFine?**:
yes

**Crash report (~/logs/latest.log)**
https://paste.ofcode.org/37w2rse4XdBrzwe5jYpVrcn

**Comment by jorgestudios** [comment]
can someone help me fix it

**Comment by jorgestudios** [comment]
hello?????

**Comment by jorgestudios** [comment]
![image](https://user-images.githubusercontent.com/80423529/235219383-2b3de587-19d4-416d-923d-75b8956389d6.png)

**Comment by SuperMartijn642** [comment]
Don't use Phosphor.
Also just be patient instead of spamming here.

**Comment by jorgestudios** [comment]
ok

**Comment by jorgestudios** [comment]
https://paste.ofcode.org/sChgmMLnJhsNCAJuAW3UZ2

**Comment by jorgestudios** [comment]
https://mclo.gs/7LdwToX
