### ISSUE TITLE
[Bug] Falling through floor, NOT using Optifine.

### ISSUE THREAD

**Issue by Boolyman** [SuperMartijn642/MovingElevators#163]
**Version Info**
- Minecraft, 1.16.5
- Moving Elevators, 1.4.0

**Are you using OptiFine?**: No

**Description of the Bug**
Player falls through floor

**Steps to Reproduce**
Add Moving Elevators to Enigmatica 6, make elevator, try to go up elevator, cry when elevator drops you to your death.

**Screenshots**
I'm not sure what you want here?  A screenshot of my death screen?

**Comment by SuperMartijn642** [comment]
Please narrow down the other mods needed to reproduce the issue.

**Comment by SuperMartijn642** [comment]
Some additional questions as well, what does your elevator cabin look like? Does this happen consistently? Are you playing on a server or just a single player world? Is there any lag when this happens?
