### ISSUE TITLE
[Crash] 1.19.4 on calling or moving elevator

### ISSUE THREAD

**Issue by Gremiger** [SuperMartijn642/MovingElevators#164]
**Version Info**
- Minecraft, 1.19.4
- Moving Elevators, 1.4.2

**Are you using OptiFine?**: No, but using Sodium, Lithium and Indium

**Steps to Reproduce**
Place the two controllers. Call the elevator or try to move the elevator, and _MOST_ times, it crashes.

**Crash report (~/logs/latest.log)**
[latest.log](https://pastebin.com/7etsrYyA)

[Client crash log](https://pastebin.com/1SGMfAPY)

**Comment by SuperMartijn642** [comment]
Should be fixed now in Moving Elevators version 1.4.3a for Minecraft 1.19.4. If the issue still persists, please let me know.
Thank you for reporting the issue!
