### ISSUE TITLE
[Crash] 1.19.2 Crash when entering the world

### ISSUE THREAD

**Issue by SplatLue19** [SuperMartijn642/MovingElevators#165]
**Version Info**
- Minecraft, 1.19.2
- Moving Elevators, 1.4.2

**Are you using OptiFine?**: Optifine with forge

**Steps to Reproduce**
Regardless of whether I wants to create a world or join an already created one, the screen keeps getting distorted after loading and then crashes, it may have something to do with the fact that I'm using tlauncher but I don't know.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/11418427/latest.log)

**Comment by SuperMartijn642** [comment]
Probably caused by OptiFine. Could you test if this crash occurs without OptiFine installed?

**Comment by SuperMartijn642** [comment]
As concluded from #166 this is caused by OptiFine. I can only suggest not using OptiFine.
