### ISSUE TITLE
[Crash] Opening world on 1.19.4 with latest version and other mods

### ISSUE THREAD

**Issue by CornishDinosaur** [SuperMartijn642/MovingElevators#166]
**Version Info**
- Minecraft, 1.19.4
- Moving Elevators, 1.4.2-forge.mc1.19.4

**Are you using OptiFine?**: Yes, with forge

**Steps to Reproduce**
Opening world with this selection of mods.

**Crash report (~/logs/latest.log)**
Put it in the following Link;
[pastebin](https://pastebin.com/xA29urnx)

**Comment by SuperMartijn642** [comment]
Probably caused by OptiFine. Could you test if this crash occurs without OptiFine installed?

**Comment by CornishDinosaur** [comment]
> Probably caused by OptiFine. Could you test if this crash occurs without OptiFine installed?

Can confirm Optifine is the cause. Sorry if I've wasted your time! :) Time for me to learn those Optifine alternatives.

**Comment by SuperMartijn642** [comment]
Yup sadly not much I can do about that.
