### ISSUE TITLE
[Bug] ... Texture Glitch on the new 1.19.2 Fabric version

### ISSUE THREAD

**Issue by RhyzzG** [SuperMartijn642/MovingElevators#167]
**Version Info**
- Minecraft, 1.19.2 fabric
- Moving Elevators, movingelevators-1.4.2-fabric-mc1.19.2.jar

**Are you using OptiFine?**: no
**Description of the Bug**
Black/Pink checker texture where the buttons and displays should be. Still functions just fine though!

**Steps to Reproduce**
placing down the block does the trick

**Screenshots**
![2023-05-22_11 31 03](https://github.com/SuperMartijn642/MovingElevators/assets/134312985/8493c865-deae-4551-a145-4ce7c6638c49)

Sorry I'm new to this but thought I would bring this to your attention!

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.9b of my core library.

Thank you for reporting the issue!
