### ISSUE TITLE
[Bug] Buttons and levers break

### ISSUE THREAD

**Issue by xFirefalconx** [SuperMartijn642/MovingElevators#169]
**Is your feature request related to a problem? Please describe.**
When I put buttons in my elevator, or levers to control specific other parts (trapdoors, etc) of the elevator, then move the elevator, they get destroyed. They are part of the elevator though! At least I wish they were... 

**Describe the solution you'd like**
You can use all buttons, levers etc within the elevator area (the one where you define the blocks that move) anywhere the elevator halts, without destroying them upon moving. 

Extra: I hope this is possible on 1.18.2 (Forge 40.2.4) because it would benefit my modpack which cannot change MC versions, obviously.

**Comment by SuperMartijn642** [comment]
That seems like a bug. What version of Moving Elevators are you using?

**Comment by xFirefalconx** [comment]
Phew then I hope it's possible to fix! 
I use 1.4.3 :)

**Comment by SuperMartijn642** [comment]
It seems to be working fine already, both buttons and levers just stay on the blocks and don't break when you move the elevator.

https://github.com/SuperMartijn642/MovingElevators/assets/12382965/dffecb76-09fa-48f1-ba69-128817c12477
