### ISSUE TITLE
Crash when adding this mod via GDLauncher (w/ workaround)

### ISSUE THREAD

**Issue by blahpers** [SuperMartijn642/MovingElevators#173]
**Version Info**
- Minecraft, ...
1.19.3
- Moving Elevators, ...
1.4.3 (Forge)

**Are you using OptiFine?**: ...
No

**Description of the Bug**
Note:  This may be a bug with how GDLauncher handles dependencies--I haven't tried other launchers--but it's the first time I've come across this.

Adding the Forge version of this mod via GDLauncher automatically adds its dependencies, Core and Config.  However, it's grabbing the Fabric version of Config for some reason, causing launch to fail.

Workaround:
After adding this mod, manually remove the Fabric version of Config, then add the Forge version of Config via GDLauncher.

**Steps to Reproduce**
See description

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Nothing I can do about that, all the files seem to be marked correctly on CurseForge and Modrinth. I guess report it to GDLauncher 🤷‍♂️
