### ISSUE TITLE
Mod conflict with Coins and Archeology Banner

### ISSUE THREAD

**Issue by Spicykurenai** [SuperMartijn642/MovingElevators#174]
**Version Info**
- Minecraft, tested on 47.1.3 and latest forge
- Moving Elevators, 1.20.1 

**Are you using OptiFine?**: ...
NO.
**Description of the Bug**
I have already let the modder for Coins and Archeology Banner know in their forum with troubleshooting support, but when I use moving elevators with the mods no banner image produces on the modded banner. I figure it is on their in, but just reporting it here for anyone else, too!
**Steps to Reproduce**
Add mods and load single or multiplayer. 

**Screenshots**
n/a only if needed

**Comment by Spicykurenai** [comment]
Darkhax said it could be the atlas to load before mod resources are available so it just loads blank textures but that it would need to be fixed on your end bc it has happened before and has been fixed.

**Comment by Spicykurenai** [comment]
an example was provided how how
![example](https://github.com/SuperMartijn642/MovingElevators/assets/140019749/7dc12fb6-d4d6-4dcb-9e01-5af3d8e89896)
 it might can be fixed

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.1.11 of my core library.
Thank you for reporting the issue!
