### ISSUE TITLE
[Bug] Mod Failed Loading crash

### ISSUE THREAD

**Issue by itsdinkd** [SuperMartijn642/MovingElevators#175]
**Version Info**
- Minecraft, 1.18.2
- Moving Elevators, 1.4.3.

**Are you using OptiFine?**: ...
No

**Description of the Bug**
Randomly crashing with Mod failed loading 

**Steps to Reproduce**
Unable to reproduce as it  is random in the public server for Another Quality Modpack 3\

**Logs**
https://gist.github.com/itsdinkd/562e687bac66e80e8c633f06f740a348

**Comment by SuperMartijn642** [comment]
As far as I can tell, it is unrelated to Moving Elevators as the point where it crashed is right before Moving Elevators gets loaded.
Could you share the `~/logs/latest.log` file? There might be an earlier error in there.

**Comment by itsdinkd** [comment]
You are right, I don’t think its moving elevators, I believe I found the culprit. Will close ticket once I get back home From: Martijn van den BrandSent: Friday, July 21, 2023 1:38 PMTo: SuperMartijn642/MovingElevatorsCc: itsdinkd; AuthorSubject: Re: [SuperMartijn642/MovingElevators] [Bug] Mod Failed Loading crash (Issue #175) As far as I can tell, it is unrelated to Moving Elevators as the point where it crashed is right before Moving Elevators gets loaded.Could you share the ~/logs/latest.log file? There might be an earlier error in there.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
