### ISSUE TITLE
[Bug] Light sources dont work on elevators

### ISSUE THREAD

**Issue by gavincapp** [SuperMartijn642/MovingElevators#176]
**Version Info**
- Minecraft, 1.19.2
- Moving Elevators, 1.14.3 Fabric 1.19.2

**Are you using OptiFine?**: No

**Description of the Bug**
While an elevator is moving, light sources on it will not emit light.

**Steps to Reproduce**
Make an elevator with a light source on it, then use the elevator.

**Screenshots**
![image_2023-07-26_181431323](https://github.com/SuperMartijn642/MovingElevators/assets/134323345/48369cfe-c5de-402b-a9b7-0ddf53d760e7)
![image_2023-07-26_181440770](https://github.com/SuperMartijn642/MovingElevators/assets/134323345/a81f2e1f-6984-409a-ad3e-79d30540fac5)

**Comment by SuperMartijn642** [comment]
This is simply a limitation of Minecraft. Minecraft does not have any sort of dynamic lighting, only actual blocks can emit light.
Nothing I can do about that sadly.
