### ISSUE TITLE
[Bug] Display and Controller camouflage broken with Chisel

### ISSUE THREAD

**Issue by atferrys** [SuperMartijn642/MovingElevators#177]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.4.3

**Are you using OptiFine?**: yes

**Description of the Bug**
Elevator Display and Controller turn invisible when using Chisel blocks to camouflage them.

**Steps to Reproduce**
Use a chisel block like `chisel:marblepillar:13` right-clicking an elevator block. The block should become invisible.

**Screenshots**
![image](https://github.com/SuperMartijn642/MovingElevators/assets/61624086/fcddbb36-6d8e-4917-90d1-e479ed73ba65)

**Comment by atferrys** [comment]
It seems to be that only blocks with connected blocks become transparent.

**Comment by SuperMartijn642** [comment]
I have improved the handling of the camouflage block now in Moving Elevators 1.4.8 which fixes the issue.
Thank you for reporting the issue!
