### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Jean-Le-Felix** [SuperMartijn642/MovingElevators#178]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.3 and 1.4.3a

**Are you using OptiFine?**: yes

**Steps to Reproduce**
Launch a game and it crashes (But not when not using optifine)

**Crash report (~/logs/latest.log)**
...
[crash-2023-07-30_14.28.33-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/12209851/crash-2023-07-30_14.28.33-client.txt)

**Comment by SuperMartijn642** [comment]
Don't use OptiFine. OptiFine changes large parts of the game, yet it is closed source so I can't know what it changes.
You can use an open source alternative like Oculus or Iris if you want shaders.

**Comment by Jean-Le-Felix** [comment]
Can you change the fullscreen resolution with Iris and Oculus?

**Comment by SuperMartijn642** [comment]
No idea
