### ISSUE TITLE
[Bug] Entities go through elevator

### ISSUE THREAD

**Issue by RMChannel** [SuperMartijn642/MovingElevators#179]
**Version Info**
- Minecraft, MohimicMC 1.20.1
- Moving Elevators, last version for Forge

**Are you using OptiFine?**: Yes, but it's on a server and optifine is on client

**Description of the Bug**
I use Ultimate Cars Mods (but also other custom entities) can't go up with elevators, in fact after 2 seconds they go down.

**Steps to Reproduce**
Simply go to the elevator with a car, you can see for yourself.

**Videoclip**

https://github.com/SuperMartijn642/MovingElevators/assets/98057423/b638ea80-ccb2-41c4-b2f1-d2c28aa26277

**Comment by SuperMartijn642** [comment]
Nothing I can do about this. The elevator simply updates the position of entities colliding with it. If those entities ignore that, there's nothing I can do 🤷‍♂️

**Comment by roberto-cito** [comment]
You have any idea how can i resolve this?

**Comment by SuperMartijn642** [comment]
You can't, it is to how Ultimate Cars Mods' entities work.
