### ISSUE TITLE
[Crash] Incompatible with Sodium 0.5.1

### ISSUE THREAD

**Issue by Ryoya15** [SuperMartijn642/MovingElevators#181]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.3a
- Fabric, 0.14.22
- Fabric API, 0.87.0

**Are you using OptiFine?**: No

**Steps to Reproduce**
1. Install Moving Elevators, its dependencies, and Sodium 0.5.1 on Fabric.
2. Launch Minecraft.
3. Minecraft crashes with exit code -1.
4. Disabling Sodium or replacing it with 0.5.0 will stop the crash.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/12331985/latest.log)

**Comment by MetaForge** [comment]
Ran into the same issue :/

**Comment by SuperMartijn642** [comment]
I've updated the Sodium compatibility to account for the changes made by Sodium.
