### ISSUE TITLE
[Bug] ...When i put some enchantments the elevator just doesn't move.

### ISSUE THREAD

**Issue by AbobusBobuss** [SuperMartijn642/MovingElevators#189]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, ...
1.4.3b-fabric-mc1.20
**Are you using OptiFine?**: ...
No
**Description of the Bug**
...Something's wrong with enchantments compabilty

**Steps to Reproduce**
...I have enchantment mod like : Enchanting Infuser, Vanilla Tweaks, Qu Enchantments, Expanded armor enchanting, Expanded Trident Enchanting, and Expanded Sword Enchanting. And when i put enchantments on the enchantment infuser its like i'm too fat for the elevator to lift

**Screenshots**
I'm trying to put a 5 second video in here but it says file size too big, sorry for that.

**Comment by AbobusBobuss** [comment]
accidentally closed it

**Comment by SuperMartijn642** [comment]
> I have enchantment mod like : Enchanting Infuser, Vanilla Tweaks, Qu Enchantments, Expanded armor enchanting, Expanded Trident Enchanting, and Expanded Sword Enchanting. And when i put enchantments on the enchantment infuser its like i'm too fat for the elevator to lift

Bruh just wut???? What does any of this have to do with Moving Elevators? How does Moving Elevators have anything to do with enchanting?

**Comment by AbobusBobuss** [comment]
i dont know

**Comment by AbobusBobuss** [comment]
it just deosnt work when i put an armor with enchantments

**Comment by AbobusBobuss** [comment]
dont ask me

**Comment by AbobusBobuss** [comment]
Im testing which enchantment is it rn
