### ISSUE TITLE
[Bug] Elevator Buttons are Broken

### ISSUE THREAD

**Issue by ZaneFlynt01** [SuperMartijn642/MovingElevators#191]
**Version Info**
- Minecraft, 1.20.2 - Quilt 0.21.0
- Moving Elevators, 1.4.3-1.4.4

**Are you using OptiFine?** No

**Description of the Bug** The textures for the buttons on the Elevator Controllers, Remote Elevator Panel, and everything else do not load, and instead show a heavily glitched spritesheet of sorts of each and every texture in the game. I am not using any custom texture packs and tried this with both 1.4.3 and 1.4.4 only to have the same issue occur twice. I even extracted the files with WinRAR and made a texture pack using all of the textures, only for it to still have issues and not work.
...

**Steps to Reproduce** Just place down any of the Mod's blocks that are added in specifically with the mod.
...

**Screenshots** blob:https://imgur.com/650a63d5-6bb7-42c9-ac37-7271c988755a
...

Mod List:
3D Skin Layers (1.5.6)
Benched (1.2.2)
Better Hand Bobbing (1.6.3)
Controlify (1.7.0-beta.2)
Energy (3.0.0 [Built into one of my other mods])
Grappling Hook Restitched (1.7)
LambDynamicLights (2.3.2)
Mod Menu (8.0.0)
Sodium (0.5.3)
Trash Cans (1.0.18)
Worthy Food (1.2.1)

Edit:
I deleted a whole bunch of mods, leaving just Sodium, Fabric API, MovingElevators, and its Dependencies), only for the issue to still not be resolved. I tried using it without sodium, but it just kinda killed my framerate, pushing me from 165 FPS down to just 60

**Comment by SuperMartijn642** [comment]
Fixed now in Moving Elevators version 1.4.4a for Fabric 1.20.2.
Thank you for reporting the issue!
