### ISSUE TITLE
[Bug] Elevator Buttons Break when you change/reload the texture pack

### ISSUE THREAD

**Issue by ZaneFlynt01** [SuperMartijn642/MovingElevators#192]
Version Info

    Minecraft, 1.20.2 - Quilt 0.21.0
    Moving Elevators, 1.4.4a

No Optifine

I had recently reported a bug I had encountered where the buttons on the blocks added in the mod were not working, and that was fixed in the 1.4.4a patch, but very quickly, I re-encountered the issue after I tried to change my texture packs. The only difference between this time and the last is that this one only shows the texture image for different beds. Most noteworthy was that the bottom-most floor's buttons would display the green bed, and then every one in the middle would use the grey bed.

To reproduce this bug, just try to change your texture pack while the mod is active.

**Comment by GeekyBakerBen** [comment]
Similar experience here where I had the Re-Imagined patch for Fresh Animations on my Resource Packs (but no longer needed it as I wasn't using Re-Imagined anymore). As soon as I took that patch off, for unknown reasons the button display panel just stopped rendering properly (could see text, but none of the background panel/button images). As soon as I put the patch back in place (despite there being no logical reason for these two things to be related in any way), the panel renders fine again...

**Comment by SuperMartijn642** [comment]
Moving Elevators keeps a reference to where on the block texture atlas its icons are located, however the reference is not updated when textures are reloaded. Hence afterwards, it is essential just using textures at a random position on the block atlas.

> As soon as I put the patch back in place (despite there being no logical reason for these two things to be related in any way), the panel renders fine again...

Due to having the same resources, it likely just so happened that Moving Elevators' icons ended up at the same location as where they were initially.

I will fix it whenever I have some time. Since the issue isn't very severe, I hadn't taken the time to do so so far.

**Comment by GeekyBakerBen** [comment]
> Moving Elevators keeps a reference to where on the block texture atlas its icons are located, however the reference is not updated when textures are reloaded. Hence afterwards, it is essential just using textures at a random position on the block atlas.
> 
> > As soon as I put the patch back in place (despite there being no logical reason for these two things to be related in any way), the panel renders fine again...
> 
> Due to having the same resources, it likely just so happened that Moving Elevators' icons ended up at the same location as where they were initially.
> 
> I will fix it whenever I have some time. Since the issue isn't very severe, I hadn't taken the time to do so so far.

Ooh, thank you for the very fast response! That's great to know. As you say, not a severe issue for now, especially as I can just keep that patch in place for now, no big problem for me :)

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.4.4a for Fabric 1.18 - 1.20.1 and 1.4.4b for Fabric 1.20.2.
Thank you both for reporting the issue!
