### ISSUE TITLE
Only allows for 7x7x7?

### ISSUE THREAD

**Issue by SethZygner** [SuperMartijn642/MovingElevators#194]
Hello, on CurseForge, it says I can make the elevator any size. And in the video shown, the elevator showcased is well above a 7x7x7 space. Is there a way I can config how big the elevator can be? Thanks a lot!

**Comment by SuperMartijn642** [comment]
The cabin size is limited to 7x7x7 by default. You can increase the limit up to 15x15x15 in the config file for Moving Elevators.

> Hello, on CurseForge, it says I can make the elevator any size.

Where does it say that?

**Comment by SethZygner** [comment]
Looking back, defiantly read that wrong. My Bad! But could you tell me the relative path to the config file? I can't seem to find it using WinRAR.

**Comment by SuperMartijn642** [comment]
It's the `config/movingelevators-common.toml` file wherever you are running the game from.

**Comment by SethZygner** [comment]
Awesome - thank you for the fast replies!
