### ISSUE TITLE
[Bug] Elevator Blocks won't change block textures.

### ISSUE THREAD

**Issue by JorgDeVie** [SuperMartijn642/MovingElevators#196]
**Version Info**
- Minecraft, Fabric 1.20.2
- Moving Elevators, Moving Elevators 1.4.5 for Fabric 1.20.2

**Are you using OptiFine?**: No, but I'm using other mods.

**Description of the Bug**
When I right-click a Elevator Controller, Remote Elevator Controller or Elevator Display, it doesn't change the block texture like they do in other versions.

**Comment by SuperMartijn642** [comment]
This seems to work fine, so my guess is that it was either caused by another mod or one the Moving Elevator updates this was reported has fixed the issue.
I'll close the issue, if you still encounter it, let me know of course.
Thank you for reporting the issue!

**Comment by SoldAuthor29067** [comment]
Hello, why has the texture of the controller, display, and remote controller changed to the boiler from the moving elevators mod? And can you tell me which mods the moving elevators mod is compatible with?
