### ISSUE TITLE
[Bug] Invisible elevator

### ISSUE THREAD

**Issue by WaterOtter86** [SuperMartijn642/MovingElevators#199]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.4.5

**Are you using OptiFine?**: no

**Description of the Bug**
Elevator is invisible while moving

**Steps to Reproduce**
Build an elevator
Run it

**Screenshots**
![Screenshot_241](https://github.com/SuperMartijn642/MovingElevators/assets/50717708/afa70b54-824c-41b4-9dd7-de0428f67d92)
![Screenshot_242](https://github.com/SuperMartijn642/MovingElevators/assets/50717708/cde6f416-fbea-49de-b4e4-b39d107adedc)

**Comment by SuperMartijn642** [comment]
This works fine with just Moving Elevators. Please narrow what other mods are needed to reproduce the issue.

**Comment by WaterOtter86** [comment]
[modlist.txt](https://github.com/SuperMartijn642/MovingElevators/files/13881791/modlist.txt)
Easier to just use dat, hmm i think having 387 mods may be a reason

**Comment by SuperMartijn642** [comment]
Please narrow down which mods are actually causing the issue. Downloading over 300 mods is too much effort for me to test 😅

**Comment by WaterOtter86** [comment]
Its Nothirium

**Comment by WaterOtter86** [comment]
Tried without nothirium, while elevators now but with a small cost on pacj performance, namely fps dropped from 75 to 2

**Comment by samasiassa** [comment]
Same issue with Nothirium installed.

**Comment by SuperMartijn642** [comment]
Nothirium, similar to Sodium and its other ports, cancels the vanilla render methods. Moving Elevators renders the elevator blocks from within those methods.
I've now added separate mixins for whenever Nothirium is installed to work around their changes.

This is available in Moving Elevators version 1.4.6.
Thank you for reporting the issue!
