### ISSUE TITLE
movingelevators-1.0.0-mc1.12 size and speed can we not change and little other bugs

### ISSUE THREAD

**Issue by Titoo8899** [SuperMartijn642/MovingElevators#2]
hi,
in your new 1.12.2 version can we place the new Elevator blocks but we can not change the speed or the size of the elevator when I click on one of the other sides. Please fix this. The other Buttons work good. And the other think is the Character Teleport on the Platform then we was to close on the elevator area. Please fix this bugs.

**Comment by SuperMartijn642** [comment]
In the current 1.12 version the GUI to change the speed and size is not implemented, but that will be done in the next release.
In order have it reliably move entities up the area where you get teleported extends quite a bit below the actual platform, I will see if I can make it any smaller.

**Comment by SuperMartijn642** [comment]
GUI has been added as of version 1.0.1 for 1.12
