### ISSUE TITLE
[1.12] Multiplayer floor names sync issue

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [SuperMartijn642/MovingElevators#20]
Non-ASCII symbols in names get replaced with `�` if client and server encoding do not match.

Singleplayer or Windows server + Windows client:
https://yurie.thigh-high.club/8imhje9f.mp4

Multiplayer, Windows client (CP1251) + Ubuntu server (UTF-8):
https://yurie.thigh-high.club/el4iwwao.mp4

**Comment by SuperMartijn642** [comment]
Ok that's gonna be a pain, I will look into that next week probably

**Comment by SuperMartijn642** [comment]
I changed the encoding to utf-16 instead of the default system encoding.
Should now be fixed in 1.2.11.

**Comment by YuRaNnNzZZ** [comment]
Yes, it works properly now. Thank you!
![изображение](https://user-images.githubusercontent.com/5104603/80284633-5e5fce00-8728-11ea-95ae-c244acc0d19d.png)
