### ISSUE TITLE
1.20.1 - game crash when creating a world with shaders enabled[Crash] ...

### ISSUE THREAD

**Issue by SeagalKru** [SuperMartijn642/MovingElevators#200]
**Version Info**
- Minecraft, ... 1.20.1
- Moving Elevators, - movingelevators-1.4.5-forge-mc1.20.1
+ supermartijn642configlib-1.1.8-forge-mc1.20
+ supermartijn642corelib-1.1.16-forge-mc1.20.1

**Are you using OptiFine?**: ... yes
- OpticManager_FORGE_v1.3.0_mc1.20
- preview_OptiFine_1.20.1_HD_U_I6_pre6

**Steps to Reproduce**
- If shaders are turned off, then he enters the world both alone and on the server (I have my own server), But if shaders are turned on, then when entering the world the client crashes (if you try to enter the server, the server continues to work). Therefore, in order to play in the world with your mod, you must first (when loading the game itself and before entering the world) disable shaders.

**Crash report (~/logs/latest.log)** ...
[crash-2024-01-15_13.45.21-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/13937987/crash-2024-01-15_13.45.21-client.txt)
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/13937989/latest.log)

**Comment by SuperMartijn642** [comment]
This is caused by OptiFine. OptiFine is closed source, so I have no way to know what it's doing.

Consider using better alternatives like [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) (for better performance) and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) (for shaders).

**Comment by SeagalKru** [comment]
It's clear.
But I use Optifine not just for beauty, but because it has a “Zoom” function (like binoculars or a telescope, only without additional crafting).
The mods you listed, in my opinion, do not provide such a function.
But, in any case, thanks for the clarification.
There will be something to think about.
As I understand it, it is useless to provide information to Optifine developers?

Update:
I'll try to communicate with the Optifine developers on their Discord.
...
