### ISSUE TITLE
[Feature] Additional check for the vanilla light block when creating an elevator cage

### ISSUE THREAD

**Issue by Tschipcraft** [SuperMartijn642/MovingElevators#201]
**Is your feature request related to a problem? Please describe.**
The light block somehow doesn't pass the air material check, so elevators won't move when a light block is in a cage, even though the elevator would most likely have no problem in phasing through them.
Since I'm developing a data pack which adds dynamic lights using the vanilla light block, this issue happens fairly often when installed with my project, but even without I think it would be nice to have the ability to move light blocks using an elevator just like e.g. structure void blocks.

**Describe the solution you'd like**
This would be an additional check in the canCreateCage method, which continues the block checking loop when it encounters a light block or straight-up excludes the block from the cage.
Thanks in advance!

**Comment by SuperMartijn642** [comment]
I have now made it so light blocks are ignored when creating the elevator cage. I have also made it so light blocks can be overwritten by the elevator to prevent light blocks created around the player whilst going up from not allowing the blocks to be placed back.

Thank you for the suggestion and hopefully fixes any inconveniences. The changes are available in version 1.4.6 of Moving Elevators.
