### ISSUE TITLE
[Crash] Game crashes when I destroy elevator controller 

### ISSUE THREAD

**Issue by bluekiwidev** [SuperMartijn642/MovingElevators#202]
**Version Info**
- Minecraft, 1.9.4 ()
- Moving Elevators, 1.4.5

**Are you using OptiFine?**: Nope.

**Steps to Reproduce**
umm i guess build a elevator that has 3 floors, place the elevator controller and break it.
Note my elevator was 7 width by 7 depth by 5 Hight, was made of iron blocks and between the 1st and 2nd controler was 12 blocks, 2nd and 3rd was 8 and 3rd and forth is 10
**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/13999723/latest.log)
[crash-2024-01-21_14.51.56-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/13999724/crash-2024-01-21_14.51.56-client.txt)

**Comment by SuperMartijn642** [comment]
Should be fixed now in Moving Elevators version 1.4.6.
Thank you for reporting the issue!
