### ISSUE TITLE
[Crash] Client crashes when a far away elevator with inbuilt Display starts moving

### ISSUE THREAD

**Issue by XAgent1990** [SuperMartijn642/MovingElevators#204]
**Version Info**
- Minecraft, 1.19.2
- Fabric, 0.14.22
- Moving Elevators, 1.4.5

**Are you using OptiFine?**: No

**Steps to Reproduce**
Build an Elevator with a display, with the elevator having a height of 2+ blocks.
If you start moving the elevator, anybody outside the renderdistance but still inside a somehow not too much greater distance than that, will have their client crash. the exact reason I can't explain.
In our case the render distance was 12 chunks, and the crashing clients were 19 chunks away.

We tested this for like two hours with four people. Sometimes having a display on the elevator doesn't caus the crash. Add one block in a specific spot and boom, game crashes.
The only way we found to always prevent this crash is for us to forbid displays on the moving elevator itself, which is a shame.
I hope you may be able to somehow fix this.

**Crash report (~/logs/latest.log)**
[crash-2024-01-22_18.14.57-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/14016138/crash-2024-01-22_18.14.57-client.txt)

**Comment by Reingerg** [comment]
Thanks for finding the error

**Comment by SuperMartijn642** [comment]
Should be fixed now in Moving Elevators version 1.4.6.
Thank you for reporting the issue!
