### ISSUE TITLE
[Crash] some kind of incompatibility with sodium 0.4.10's rendering code ?

### ISSUE THREAD

**Issue by uczpre** [SuperMartijn642/MovingElevators#206]
it kept refering to moving elevators , ive tried deleting the config file of moving elevators.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-02-03 12:38:55
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_761.handler$fff000$sodium$init(class_761.java:13469)
	at net.minecraft.class_761.<init>(class_761.java:307)
	at net.minecraft.class_310.<init>(class_310.java:583)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [movingelevators.mixins.json:sodium.SodiumWorldRendererMixin from mod movingelevators] from phase [DEFAULT] in config [movingelevators.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on renderLevelBlockEntities could not find any targets matching 'Lme/jellysquid/mods/sodium/client/render/SodiumWorldRenderer;renderBlockEntities(Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;F)V' in me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer. Using refmap movingelevators.mixins.refmap.json [PREINJECT Applicator Phase -> movingelevators.mixins.json:sodium.SodiumWorldRendererMixin from mod movingelevators -> Prepare Injections ->  -> handler$ebi000$movingelevators$renderLevelBlockEntities(Lnet/minecraft/class_4587;Lnet/minecraft/class_4599;Lit/unimi/dsi/fastutil/longs/Long2ObjectMap;Lnet/minecraft/class_4184;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_761.handler$fff000$sodium$init(class_761.java:13469)
	at net.minecraft.class_761.<init>(class_761.java:307)
	at net.minecraft.class_310.<init>(class_310.java:583)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-86-generic
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 387890960 bytes (369 MiB) / 1174405120 bytes (1120 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5958.02
	Virtual memory used (MB): 3348.38
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 50.00
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.5
		advancementplaques: Advancement Plaques 1.4.11
		advancementscreenshot: Advancement Screenshot 4.3
		adventurez: AdventureZ 1.4.19
		anger-management: Anger Management Mod 2.0.1-1.20.1
		appleskin: AppleSkin 2.5.1+mc1.20
		aquamirae: Aquamirae 6
		architectury: Architectury 9.1.12
		artifacts: Artifacts 9.2.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		asbestos: Asbestos 0.2.0
		automobility: Automobility 0.4.2+1.20.1-fabric
			jsonem: JsonEM 0.2.1+1.20
		axolotlbuckets: Axolotl Buckets 1.2.0
		azurelib: AzureLib 2.0.12
		badpackets: Bad Packets 0.4.3
		bedspreads: Bedspreads 6.2.0+1.20.1
		betterbeds: Better Beds 1.3.0
		blockofsky: Block Of Sky 0.3.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.4-1.20.1
			maelstrom_library: Maelstrom Library 1.6.1-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		botarium: Botarium 2.3.1
			team_reborn_energy: Energy 3.0.0
		bygonenether: Bygone Nether 1.3.2
		cakedelight: Cake Delight 1.20.1-v3.0.2
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.7
		cat_jam: cat_jam 1.2.1
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.30
		conduitspreventdrowned: Conduits Prevent Drowned 3.6
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		corgilib: CorgiLib 4.0.0.4
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		crawl: Crawl 0.12.0
			mm: Manningham Mills 2.3
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		createbigcannons: Create Big Cannons 0.5.3.b-nightly-8a45d8e
			ritchiesprojectilelib: Ritchie's Projectile Library 1.0.0-369e88d+1.20.1-fabric
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		diagonalfences: Diagonal Fences 8.1.2
			diagonalblocks: Diagonal Blocks 8.0.2
		disco: Disco — Custom Music Discs 2.0.8
		distanthorizons: Distant Horizons 2.0.1-a
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		elementa: Elementa 619
		eleven_music_disc: Eleven Music Disc 1.0
		enchantsmith: Enchantsmith fabric-1.0.3-1.20
		endrem: End Remastered 5.2.2
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		essential: Essential 1.3.0.1+g24ea70f4b2
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		etcher: Etcher 1.2.0
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		fabrishot: Fabrishot 1.10.0
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmersrespite: Farmer's Respite 2.3.4
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		fishofthieves: Fish of Thieves 3.0.3
		fishontheline: Fish On The Line 3.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		fps: FPS Monitor 1.20-1.3.0-Fabric
		friendsandfoes: Friends&Foes 1.9.9
		frightsdelight: Frights Delight 1.20.1-1.0.1
		geckolib: GeckoLib 4 4.4
			com_eliotlash_mclib_mclib: mclib 20
		genshinstrument: Genshin Instruments 3.3.1
		geodes: More Geodes 1.8.2
		globalxp: Global XP 1.10.4
		graveyard: The Graveyard 2.9.1
		guardvillagers: GuardVillagers 2.0.8-1.20.1
			porting_lib_common: Porting Lib Common 2.1.1127+1.20
		hangglider: Hang Glider 8.0.1
		hauntedharvest: Haunted Harvest 1.20-3.1.11
		highlighter: Highlighter 1.1.6
		hybrid-aquatic: Hybrid Aquatic 1.1.0
		iceberg: Iceberg 1.1.18
		illagerinvasion: Illager Invasion 8.0.3
			extensibleenums: Extensible Enums 7.0.1
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		indium: Indium 1.0.21+mc1.20.1
		jade: Jade 11.6.1
		java: OpenJDK 64-Bit Server VM 17
		jingle: Jingle 1.0.2
		jumpfastuse: jumpfastuse 1.0
		kiwi: Kiwi Library 11.5.4
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		manure: Manure 3.3
		memoryleakfix: Memory Leak Fix 1.1.2
		midnightcontrols: MidnightControls 1.8.2+1.20
			midnightlib: MidnightLib 1.4.1
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		minecells: Mine Cells 1.6.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		minecraft: Minecraft 1.20.1
		mixtape: Mixtape 1.6.1
		moblassos: Mob Lassos 8.0.0
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.84
		morebows: More Bows Restrung 1.0.11+1.20.x
		morechathistory: MoreChatHistory 1.1.1
		movingelevators: Moving Elevators 1.4.5
		mr_cherry_villages: Cherry Grove Villages 1.0.3
		mr_ctov_gazebocompat: CTOV - Gazebo compat 1.0
		mutantmonsters: Mutant Monsters 8.0.4
		mvs: Moog's Voyager Structures 4.1.1-1.20-fabric
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		no-telemetry: No Telemetry 1.7.0
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		obscure_api: Obscure API 16
		org_jetbrains_annotations: annotations 13.0
		owo: oωo 0.11.2+1.20
		perfectplushies: Perfect Plushies 1.9.0
		philipsruins: Philip`s Ruins 1.20.1
		ping-wheel: Ping Wheel 1.7.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		plentyplates: Plenty Plates 8.0.0
		pumpkillagersquest: Pumpkillager's Quest 3.6
		puzzleslib: Puzzles Lib 8.1.13
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		quartzelv: Quartz Elevator 2.2.5+1.20
		raised: Raised 3.1.0
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.0.674
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		smallships: Small Ships 2.0.0-a2.3.3
		smartbrainlib: SmartBrainLib 1.12
		snowrealmagic: Snow! Real Magic! 9.0.4
		snowyspirit: Snowy Spirit 1.20-2.2.6
		sodium: Sodium 0.4.10+build.27
		spell_engine: Spell Engine 0.12.4+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		spelunkery: Spelunkery 1.20.1-0.3.5
		starlight: Starlight 1.1.2+fabric.dbc156f
		status-effect-bars: Status Effect Bars 1.0.3
		styled-nicknames: Styled Nicknames 1.2.1+1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.2+1.19.3
			player-data-api: Player Data API 0.2.2+1.19.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.7.17
			mixinsquared: MixinSquared 0.1.1
		suppsquared: Supplementaries Squared 1.20-1.1.12
		tcdcommons: TCD Commons API 3.5+fabric-1.20.1
		tenshilib: TenshiLib 1.20.1-1.7.2
		the_bumblezone: The Bumblezone - Fabric 7.1.14+1.20.1-fabric
			athena: Athena 3.1.1
			noindium: No Indium? 1.1.0+1.20
		tlc: The Lost Castle 1.0.1
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.8
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.1
			org_reflections_reflections: reflections 0.10.2
		tree-hollows: Tree Hollows 3.1.0
		treechop: HT's TreeChop 0.18.3
		trinkets: Trinkets 3.7.1
		universalcraft: UniversalCraft 318
		urlmusicdiscs: URL Music Discs 1.1.0
			net_lingala_zip4j_zip4j: zip4j 2.11.5
		valkyrienskies: Valkyrien Skies 2 2.1.3-beta.1
		vigilance: Vigilance 295
		vs_eureka: VS Eureka Mod 1.3.0-beta.4
		wthit: wthit 8.5.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
	Flywheel Backend: Uninitialized
	Launched Version: fabric-loader-0.15.6-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce MX150/PCIe/SSE2 GL version 3.2.0 NVIDIA 545.29.02, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by SuperMartijn642** [comment]
That's a very old version of Sodium, please update to a newer version.
Also, please fill in the template.
