### ISSUE TITLE
[Crash] Server hangs when chunk with elevator block is loaded

### ISSUE THREAD

**Issue by Allazeu** [SuperMartijn642/MovingElevators#207]
**Version Info**
- Minecraft, 1.16.5
- Moving Elevators, 1.4.5

**Are you using OptiFine?**: Yes (client), no (server)

**Steps to Reproduce**
This happens sporadically, I fixed this issue twice before (1st removing a structure mod, 2nd changing server command-line args). I have no idea how to reproduce this because this only happens specifically with my world.

**Crash report (~/logs/latest.log)**
[2024-02-05-5.log](https://github.com/SuperMartijn642/MovingElevators/files/14189834/2024-02-05-5.log)

I don't even know if I should be calling this a crash or a bug, because it makes the server hang (does not crash server because server has max-tick-time set to -1). The only reason I believe this is MovingElevators is because I used a different mod (ModernFix) to tell me what is causing the server to hang. Without the mod, I was not able to pinpoint what mod was causing the server to hang since the normal minecraft server log did not give me the proper information.

The line of interest was:
`at com.supermartijn642.movingelevators.blocks.CamoBlock.func_200011_d(CamoBlock.java:120) ~[movingelevators:?]`

**Comment by SuperMartijn642** [comment]
Should be fixed now in Moving Elevators version 1.4.6.
Thank you for reporting the issue!
