### ISSUE TITLE
[Bug] Elevator does not move

### ISSUE THREAD

**Issue by codexp** [SuperMartijn642/MovingElevators#208]
**Version Info**
- Minecraft, v1.20.2
- Moving Elevators, v1.4.5

**Are you using OptiFine?**: yes

**Description of the Bug**

Elevators stop working as soon as `minecraft:light` (invisible light source) is placed in elevator.

**Steps to Reproduce**

Place invisible light source `minecraft:light` inside the cabin or anywhere in the shaft.

**Screenshots**
![2024-02-13_03 51 12](https://github.com/SuperMartijn642/MovingElevators/assets/6502486/8b7352d9-3827-42c2-8257-6eb9cec9ec87)

**Comment by SuperMartijn642** [comment]
Light sources won't be moved by the elevator as they shouldn't be movable in survival. In version 1.4.6, light sources are treated as air and simply left behind, please update Moving Elevators.
