### ISSUE TITLE
[1.15.2] Double-Slabs Issue

### ISSUE THREAD

**Issue by realTIMematrix** [SuperMartijn642/MovingElevators#21]
Hi,

I'm using forge 31.1.48 and about 115 other mods. One of this mods is the lost cities mod from mcjty.
When you place a elevator controller on the floor of a double smooth stone slab it works upwards, but also it produces at the same time the double stone slaps on the upwards floor and on the ground so that when you stand on the elevator you get damage. with normal block it works fine, but not with double slabs

affected version: movingelevators-1.2.10-mc1.15

regards

**Comment by SuperMartijn642** [comment]
Are these the vanilla stone slabs?
Do the slab blocks have some sort of protection preventing you from breaking them?
Could you upload a log file so I can see if there are any errors?
Does this only happen near lost cities structures or everywhere in the world?
Edit: Slabs work fine without other mods, I think might be an issue with The Lost Cities as it's still in beta. I will test it myself tomorrow.

**Comment by realTIMematrix** [comment]
**Are these the vanilla stone slabs?**
Yes, Smooth Stone Slabs
**Do the slab blocks have some sort of protection preventing you from breaking them?**
I don't use a mod which only breaks one slab. If you break the slabs with a pickaxe, both (up and downside) weill break. You can place it different like it is in vanila.
**Could you upload a log file so I can see if there are any errors?**
Will take a look if some error appear
**Does this only happen near lost cities structures or everywhere in the world?**
It doesn't matter if there is a lost cities structure or not. It seems that the behavior of slabs is different. If i put slabs on the upper side it works, if i put slab on the down side the elevator did not work. if i make a mix of both (upper and downside) it produces ghost blocks.

**Edit: Slabs work fine without other mods, I think might be an issue with The Lost Cities as it's still in beta. I will test it myself tomorrow.**
Thanks a lot.

Suggustion: How do I recall a elevator when the elevator is up but can't reach the elevator controller because the elevator platform is to large?

**Comment by SuperMartijn642** [comment]
**How do I recall an elevator when the elevator is up but can't reach the elevator controller because the elevator platform is to large?**
Currently you can only use redstone for this, but I will be adding a button block, just like the elevator controller, that can be linked to an elevator controller and can be placed anywhere.

Any blocks which have a solid top, like the top face of a full block, will work for the platform. The bottom half of a slab block will thus not work, but the top half will. Anyways it shouldn't produce ghost blocks when combining them, I will look into that.

**Comment by SuperMartijn642** [comment]
So no matter what I do, I can't move the elevator with only the bottom half slabs, even if I mix them with top halfs.
Could you send a screenshot of your platform configuration?

**Comment by realTIMematrix** [comment]
Sorry if i wrote it difficult. An elevator 3x3 elevator with only one bottom slab don't work. It work only when you place an additional slab on top.

**Comment by SuperMartijn642** [comment]
Do you also happen to be using this mod https://www.curseforge.com/minecraft/mc-mods/double-slabs?

**Comment by SuperMartijn642** [comment]
I can't replicate the issue, do you mean when you have the platform like [this](https://imgur.com/4tM6wl9)?

**Comment by realTIMematrix** [comment]
> Do you also happen to be using this mod https://www.curseforge.com/minecraft/mc-mods/double-slabs?

No, not using this mod

**Comment by realTIMematrix** [comment]
> I can't replicate the issue, do you mean when you have the platform like [this](https://imgur.com/4tM6wl9)?

I try to replicate it and found where the problem is. I will try to describe it as best as possible.
All steps are done in creative.

1. Place Elevator controller (with default settings 3x3 and normal speed)  on any double slab floor in a lost cities map 
2. Place some stoneblocks on top of the elevator block to get the required heigh (10 blocks up)
3. Place second elevator block on top of the stone block.

Until this the elevator works fine.

4. Platform should be on floor 1 and break the controllor on floor 0.  place a new elevator controller on the same place as before (floor 0)
5. use the elevator.

It seems that when you break accidently one of the controllor blocks the complete elevator is broken and you have to replace all elevator blocks. don't know if this is true but this are the steps to reproduce this issue.

But if you can't reproduce it don't waste to much time. For me it is ok to close this but if more persons have the same problems you can invest more time for investigation :-)

thank you

**Comment by SuperMartijn642** [comment]
Are you talking about the elevator going through blocks?

**Comment by realTIMematrix** [comment]
Yes, the elevator go through block. But i think that only happens sometimes and i have also a situation where this problem fixes itself...very strange :-)

**Comment by SuperMartijn642** [comment]
As mentioned in the FAQ
> My elevator just went through a block, is this normal?
> Yes, the platform will ignore blocks not at floor level. This is for performance reasons, as checking hundreds of blocks every tick is not a good idea
