### ISSUE TITLE
[Bug] my anti virus says that core lib have trojan virus

### ISSUE THREAD

**Issue by mrmialczykont** [SuperMartijn642/MovingElevators#211]
**Version Info**
- Minecraft 1.12.2
- Moving Elevators, 1.4.6

**Are you using OptiFine?**: no

**Description of the Bug**
 my antivirus says that it has virus

**Steps to Reproduce**
idk

**Screenshots**
dont have

**Comment by SuperMartijn642** [comment]
I will need at least some info, this is pretty much useless.

Your title says 'my anti virus says that core lib have trojan virus' and the bug description says 'my antivirus says that it has virus'. What is being reported as a virus, Moving Elevators or my core library? If my core library, then why report it as a bug with Moving Elevators?
What antivirus program? What is it being reported as?

Overall, there's not much I can do about this. It is just another false positive and you can report it as so.
If you don't trust me, the code for all my mods is public and you can even build the mods yourself to verify the ones uploaded to CurseForge and Modrinth.
