### ISSUE TITLE
This issue of mine doesn't land anywhere in the option GitHub gave me so here it is.

### ISSUE THREAD

**Issue by JamjamSA** [SuperMartijn642/MovingElevators#214]
**Question**
Basically, I saw in that GIF that you can expand your elevator to 11 blocks. Why is mine capped at 7 and how can I extend that?

**Comment by SuperMartijn642** [comment]
The default limit is a 7 by 7 by 7 area for the cabin in order to avoid creating too much lag on servers. You can increase the limit up to 15 by 15 by 15 in the config file for Moving Elevators.
The config is located at `configs/movingelevators-common.toml` next to your mods folder.

**Comment by JamjamSA** [comment]
> The default limit is a 7 by 7 by 7 area for the cabin in order to avoid creating too much lag on servers. You can increase the limit up to 15 by 15 by 15 in the config file for Moving Elevators. The config is located at `configs/movingelevators-common.toml` next to your mods folder.

Nice. Thanks
