### ISSUE TITLE
[Bug] Elevators are rendered way outside the player/server view distance.

### ISSUE THREAD

**Issue by Chesvin1** [SuperMartijn642/MovingElevators#215]
**Version Info**
- Minecraft 1.16.5 - Forge _36.2.42_
- Moving Elevators-1.4.6

**Are you using OptiFine?**: No.

**Description of the Bug**
Elevators can be rendered outside the player or server render distance. Although this shouldn't have a big impact on performance, this shouldn't be desired behavior as it can reveal things that the player shouldn't really see. 

The render distance of the elevators should be tied to the player's render distance.

**Steps to Reproduce**
Create an elavator, go outside the render distance, and press F3+B, you will be able to see the hitbox. Also, if the elevator is moving, the player will be able to see them. 

**Screenshots**

![2024-04-12_16 46 43](https://github.com/SuperMartijn642/MovingElevators/assets/68168061/0a8956a9-6b24-4470-a9be-c172980cc927)

![image](https://github.com/SuperMartijn642/MovingElevators/assets/68168061/9eb1693b-6c86-40b6-bd9f-b58339ea2ccd)

**Comment by SuperMartijn642** [comment]
The render distance for the elevators was simply a fixed 300 blocks.
In version 1.4.7 it is now bound to the actual render distance setting, so this should no longer be an issue.
Thank you for reporting the issue!
