### ISSUE TITLE
[Bug] Camouflaging elevator blocks doesn't work.

### ISSUE THREAD

**Issue by MonochromeOS** [SuperMartijn642/MovingElevators#217]
**Version Info**
- Minecraft, 1.20.4
- Moving Elevators, 1.4.6

**Are you using OptiFine?**: No

**Description of the Bug**
Trying to camouflage elevator blocks doesn't work. I've tried to do this on multiple worlds.

**Steps to Reproduce**
1. Place down an elevator block of any kind.
2. Attempt to camouflage it as another block.

**Screenshots**
https://github.com/SuperMartijn642/MovingElevators/assets/108891444/87833d7b-a920-4ee7-b06e-f967aecde508

**Comment by SuperMartijn642** [comment]
This works fine with just Moving Elevators installed. Could you narrow down which other mods are needed to reproduce the issue?
Also what modloader are you using?

If you are using Sodium, you will of course have to install Indium if you haven't already.

**Comment by OhNoWhyIsThisHappening** [comment]
> This works fine with just Moving Elevators installed. Could you narrow down which other mods are needed to reproduce the issue? Also what modloader are you using?
> 
> If you are using Sodium, you will of course have to install Indium if you haven't already.

I'm having the same issue on my modded java realm, 1.20.4, I cannot place any of the elevator blocks.

**Comment by SuperMartijn642** [comment]
@OhNoWhyIsThisHappening how is that even remotely the same issue? Also, you cannot have a modded realm, you don't have access to the server, so you can't install mods on it.

**Comment by OhNoWhyIsThisHappening** [comment]
> @OhNoWhyIsThisHappening how is that even remotely the same issue? Also, you cannot have a modded realm, you don't have access to the server, so you can't install mods on it.

also the same issue because I can't place down elevator blocks.

Uh yeah you can? I'm literally playing on it rn.

This video shows you how
https://youtu.be/K_vep_lQUrA?si=yXrHUcGilEmNe6yy

**Comment by SuperMartijn642** [comment]
> also the same issue because I can't place down elevator blocks.

That is not at all what the issue is about, read it.

> Uh yeah you can? I'm literally playing on it rn.

Yeah I wonder why you can't place down any blocks from Moving Elevators then. Of course you can install mods on your client and join the realm. You can join any server with mods installed on your client.
That realm is just a vanilla server, you cannot install mods on it as you don't have access to the server.

> This video shows you how
https://youtu.be/K_vep_lQUrA?si=yXrHUcGilEmNe6yy

That does not work.

**Comment by Rakusa05** [comment]
I have the same issue, but on the same server with mostly the same mods (some client side mods difference) and config it works for my friends. I was going to spend sometime eventually to figure out what is causing this, i'll try to do that soon.

I have quickly tried disabling my shaders and removing all my resource pack. I also removed iris and distant horizon. This didnt help.

In the mean time if this info can help i'm on fabric 1.20.4 and moving elevator 1.4.6

**Comment by Rakusa05** [comment]
I found the culprit causing the problem (for me), it's modernfix-fabric-5.15.0+mc1.20.4. Removing the mod fixes the problem. I tried a few option in it, but it doesnt save the settings. Hopefully MonochromeOS has that mod too.

**Comment by SuperMartijn642** [comment]
Could you check if updating to the latest version of ModernFix, 5.16.1, fixes the issue?

**Comment by Rakusa05** [comment]
5.16.1 still has the same issue

**Comment by MonochromeOS** [comment]
I can confirm that I have modernfix installed, although I'm not at home right now so I can't test to see if that's the only mod causing problems. I'll post another comment here in a few hours once I get the chance to test it.

**Comment by MonochromeOS** [comment]
Just hopped into a world and tried block camouflaging after removing ModernFix, and it works! Not sure what the problem is, but I suppose it would be a good idea to mark it as an incompatibility. Especially since it's a part of the most popular optimization modpack for Fabric currently (Fabulously Optimized.)

**Comment by SuperMartijn642** [comment]
I tried to reproduce the issue with ModernFix 5.16.1, but the camouflaging appears to work fine:
![image](https://github.com/user-attachments/assets/34ac3653-1120-45aa-aa2c-2e754e381679)
