### ISSUE TITLE
[Bug] Block & Level glitch

### ISSUE THREAD

**Issue by YeetboiPro** [SuperMartijn642/MovingElevators#218]
**Version Info**
- Minecraft, 1.20.1 Forge
- Moving Elevators, 1.4.7 from 4/22/24

**Are you using OptiFine?**: No

**Description of the Bug**
When I move my elevator up two or more floors, it refuses to go back down when I press the down button but can continue to go up. When I call it from multiple floors down, it glitches out and not only breaks a near fully enclosed elevator but also mis-levels with the controller blocks. It also does this glitch with the opposite motion occasionally.

**Steps to Reproduce**
Listed in the description. Use a 3x3 block area to make it easy.

**Screenshots**
Videos I took are too big to attach here despite only being 20-30 seconds long (250mb+)

**Comment by SuperMartijn642** [comment]
Just building an elevator and moving it up or down seems to work fine, so I can't really replicate this.
Are there any errors in the `logs/latest.log` file from loading the world to using the elevator to saving the world again?

> Videos I took are too big to attach here despite only being 20-30 seconds long (250mb+)

Could you upload a video of it to some other platform maybe? For example Imgur, Google Drive, or an unlisted video on YouTube
