### ISSUE TITLE
[Bug] ... Why does my screen do this when im using a shaderpack?

### ISSUE THREAD

**Issue by RickHZ69** [SuperMartijn642/MovingElevators#220]
**Version Info**
- Minecraft, ...
- Moving Elevators, ...

**Are you using OptiFine?**: ...
yes
**Description of the Bug**
my screen looks like its on drugs

**Steps to Reproduce**
make an elevator and have shaders on

**Screenshots**
![Uploading Screenshot 2024-05-25 232206.png…]()

**Comment by RickHZ69** [comment]
![Uploading image.png…]()

**Comment by RickHZ69** [comment]
idk how too add a picture

**Comment by SuperMartijn642** [comment]
Well there is nothing I can do with this.
