### ISSUE TITLE
[Bug] Compatibility with Vintagium

### ISSUE THREAD

**Issue by sakuraimikoto33** [SuperMartijn642/MovingElevators#224]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.4.7

**Are you using OptiFine?**: no

**Description of the Bug**
When used with Vintagium, the elevator is not displayed.
https://github.com/Asek3/sodium-1.12/issues/44

**Comment by SuperMartijn642** [comment]
I added support for Vintagium now in Moving Elevators version 1.4.8. Thank you for reporting the issue!
