### ISSUE TITLE
[Crash] Crash with Elytra Trims (Tracking)

### ISSUE THREAD

**Issue by Baylem** [SuperMartijn642/MovingElevators#228]
**Version Info**
Minecraft Version: 1.21
Moving Elevators: 1.4.7
Fabric Loader: 0.16.0

**Are you using OptiFine?**: No

**Steps to Reproduce**
1. Install Moving Elevators Mod with Dependencies
2. Install Elytra Trims Mod
3. Join multiplayer server
4. Disconnect

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-08-04 01:59:33
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
```

**MAJOR DISCLAIMER:** This is created purely for tracking, as this crash also happens with Traveler's Backpacks (and dependencies) with Elytra Trims.

Elytra Trims issue: https://github.com/kikugie/elytra-trims/issues/67

**Comment by SuperMartijn642** [comment]
As mentioned in https://github.com/kikugie/elytra-trims/issues/67, I believe the issue is caused by a mixin from Elytra Trims and is the issue is unrelated to Moving Elevators.
Still, thank you for reporting the issue of course 🙂
