### ISSUE TITLE
[Bug] Some blocks in cabin visually tilting when moving [Fabric 1.21]

### ISSUE THREAD

**Issue by jshipley** [SuperMartijn642/MovingElevators#229]
**Version Info**
- Minecraft 1.21
- Fabric Loader 0.16.0
- Fabric API 0.100.8+1.21
- Moving Elevators 1.4.7

**Other Mods Installed**
- Fabric API
- SuperMartijn642's Config Library
- SuperMartijn642's Core Lib

**Are you using OptiFine?**: no

**Description of the Bug**
When the elevator is moving, some blocks such as doors, trapdoors, and copper grates visually tilt. Standing on them still works as if they were not tilting. Looking around changes the tilt direction

**Steps to Reproduce**
- Build elevator with copper grates.
- Move elevator

**Screenshots**
...
![2024-08-04_11 23 20](https://github.com/user-attachments/assets/5eccae5f-e2b0-4216-ab38-999f4d2b804b)

**Comment by SuperMartijn642** [comment]
It is fixed now in Moving Elevators version 1.4.7a.
Thank you for reporting the issue!
