### ISSUE TITLE
Game crash with latest mod update

### ISSUE THREAD

**Issue by traveldesign** [SuperMartijn642/MovingElevators#23]
Hi, I installed the latest 1.15.2 file and now when I try to interact with the control block the game freezes and crashes. I included the crash report. For now I've gone back to the previous version of the file and it doesn't crash.
[crash-2020-04-28_17.48.02-server.txt](https://github.com/SuperMartijn642/MovingElevators/files/4549419/crash-2020-04-28_17.48.02-server.txt)

**Comment by SuperMartijn642** [comment]
What Forge version are you using?
Could you try redownloading the latest version, because I reuploaded it after a few hours to fix this issue. You might have beaten me to it when you downloaded the latest version.
Edit: I can see the forge version is up to date, so that shouldn't be causing any issues.

**Comment by lebanni** [comment]
Same here, both client and server.
[crash-2020-04-30_04.41.03-server.txt](https://github.com/SuperMartijn642/MovingElevators/files/4555852/crash-2020-04-30_04.41.03-server.txt)

[crash-2020-04-30_04.43.10-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/4555855/crash-2020-04-30_04.43.10-client.txt)

In fact, v1.2.12 is also crashing the same way.

**Comment by SuperMartijn642** [comment]
Do you also happen to be using Packed Up?
Edit: If so, could you see if updating Packed Up fixes it?

**Comment by SuperMartijn642** [comment]
@traveldesign You're crash is unrelated from @lebanni, does updating to version 1.2.13 fix it?

**Comment by lebanni** [comment]
Doesn't crash anymore with both latest versions
