### ISSUE TITLE
[Bug] Remote panel

### ISSUE THREAD

**Issue by sburdix** [SuperMartijn642/MovingElevators#234]
**Version Info**
- Minecraft 1.20.1
- Moving Elevators 1.4.8

Are you using OptiFine? No

**Description of the Bug**
When I bound my remote control panel, if I try to place it then I get the message as if it was not bound to the first block

**Comment by SuperMartijn642** [comment]
What modloader are you playing on?

**Comment by sburdix** [comment]
> What modloader are you playing on?

Forge

**Comment by SuperMartijn642** [comment]
It appears to be working fine:

https://github.com/user-attachments/assets/583cdb4c-c86b-477f-bcaa-dfce02261526

**Comment by sburdix** [comment]
[[](url)](https://youtu.be/Wx5dn8S6tec) i posted a video of my problem, sorry for the quality, hope it helps.

**Comment by SuperMartijn642** [comment]
Does it show that it is bound on the item?
![image](https://github.com/user-attachments/assets/7cc5f442-865f-4e7f-b919-37404c578c17)
Can you unbind it by shift-right-clicking the item?
![image](https://github.com/user-attachments/assets/22d33b5e-9cb6-4281-a60f-b6c3b59cfe40)
Does it show anything, like errors, in the logs? Are you playing on a server or in single player?

**Comment by sburdix** [comment]
> Does it show that it is bound on the item? ![image](https://private-user-images.githubusercontent.com/12382965/364186139-7cc5f442-865f-4e7f-b919-37404c578c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTE1NTMsIm5iZiI6MTcyNTQxMTI1MywicGF0aCI6Ii8xMjM4Mjk2NS8zNjQxODYxMzktN2NjNWY0NDItODY1Zi00ZTdmLWI5MTktMzc0MDRjNTc4YzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAwNTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTJhYzE2N2QwNWIyZTNkNWE1NGQ2YTQyZDgwZWE1MThlMDg5N2Q2ODFlNTA1NmU4YzEzNGRiMzJiYjY5M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9zzZ75A0rHdrwMCIoRiXJ4HjOCFnvHCoUXFEXSEMnKc) Can you unbind it by shift-right-clicking the item? ![image](https://private-user-images.githubusercontent.com/12382965/364186264-22d33b5e-9cb6-4281-a60f-b6c3b59cfe40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTE1NTMsIm5iZiI6MTcyNTQxMTI1MywicGF0aCI6Ii8xMjM4Mjk2NS8zNjQxODYyNjQtMjJkMzNiNWUtOWNiNi00MjgxLWE2MGYtYjZjM2I1OWNmZTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAwNTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1M2U0OTYwNTFhZmM5YmZiNWFkZTk5ZmZiYjkwNGQ0ZGZlMmYzZDdjZjUwMjQ4ZWVmZmZjMTFlY2NmZWE0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2P3x6IDePgilVsrnOB-cqc6r-k-CVDQ0sjefXn1a2H4) Does it show anything, like errors, in the logs? Are you playing on a server or in single player?

No, when I bind it the text prompt is the usual blue one "can be bound". For such reason it also can't be unbound. I'm playing single player. Where can I see the logs?

**Comment by SuperMartijn642** [comment]
The logs are at `logs/latest.log` next to your mods folder. Feel free to just drop the file in here and then I will have a look.
At this point I would have to guess it is probably some other mod you have preventing you from interacting with the block properly.

It is currently the middle of the night for me, so I will probably look through it tomorrow

**Comment by sburdix** [comment]
Understood. It is night for me as well, so now I'll add my latest log for you to look at when you have the time for it. Thank you for your help.
[log.txt](https://github.com/user-attachments/files/16859488/log.txt)

**Comment by SuperMartijn642** [comment]
Nothing related to Moving Elevators in the logs.
Can you reproduce the issue in a new world?
And can you reproduce the issue with just Moving Elevators installed? If not, can you narrow down which other mod is needed to reproduce the issue?

**Comment by sburdix** [comment]
I just give it a try on a new world, with just your mod and the associated libraries, and it worked. As you assumed, some other mod I have installed conflicts with yours. Is there any way to fix this?

**Comment by SuperMartijn642** [comment]
Can you narrow down which mod is causing it? I would have to know which mod causes it in to try and figure out why

**Comment by sburdix** [comment]
> Can you narrow down which mod is causing it? I would have to know which mod causes it in to try and figure out why

How do I narrow it down? I'm not that great with modding so idk

**Comment by SuperMartijn642** [comment]
Enable all mods and check that the issue is there. Then:
- Disable half the mods (besides Moving Elevators ofc)
- If the issue persists, repeat with the mods still enabled, if the issue goes away, repeat with the mods you just disabled

Eventually you will narrow it down to a single mod (+ dependencies maybe)

**Comment by sburdix** [comment]
This is going to take some time. Thank you for your help, when I'll find out I'll let you know for sure.

**Comment by sburdix** [comment]
It's not the mods. When, without disabling any mod, I create a new world, it works just fine. You can close the thread, I give up.

**Comment by SuperMartijn642** [comment]
Ah that's why I originally asked if you could reproduce the issue in a new world.
Could you replace the version of Moving Elevators you currently have with this one:
https://drive.google.com/file/d/1ok_6sikYTweahLF-R3xxgDyseBOzrqTO/view?usp=sharing
It logs some additional info. Then load your original world where the issue is present, right click with the remote elevator panel item on the elevator controller, and then try to place the remote elevator panel.
Then, can you send me the new `logs/latest.log` from that?

**Comment by sburdix** [comment]
> Ah that's why I originally asked if you could reproduce the issue in a new world. Could you replace the version of Moving Elevators you currently have with this one: https://drive.google.com/file/d/1ok_6sikYTweahLF-R3xxgDyseBOzrqTO/view?usp=sharing It logs some additional info. Then load your original world where the issue is present, right click with the remote elevator panel item on the elevator controller, and then try to place the remote elevator panel. Then, can you send me the new `logs/latest.log` from that?

Will do in a few hours.

**Comment by sburdix** [comment]
Here I am, sorry for the wait.
[latest.log](https://github.com/user-attachments/files/16875264/latest.log)

**Comment by SuperMartijn642** [comment]
Hmm there seems to be nothing in the log regarding interacting with the elevator controller or remote elevator panel.
> Then load your original world where the issue is present, right click with the remote elevator panel item on the elevator controller, and then try to place the remote elevator panel.

Did you interact with the blocks?
If so, it is probably some other mod suppressing the logs. In that case would you be able to do the same again with this file 😅
https://drive.google.com/file/d/1b1gK5ZTmNfCgFiAuNdZm8ljQHuMcaRLO/view?usp=sharing

**Comment by sburdix** [comment]
> Hmm there seems to be nothing in the log regarding interacting with the elevator controller or remote elevator panel.
> 
> > Then load your original world where the issue is present, right click with the remote elevator panel item on the elevator controller, and then try to place the remote elevator panel.
> 
> Did you interact with the blocks? If so, it is probably some other mod suppressing the logs. In that case would you be able to do the same again with this file 😅 https://drive.google.com/file/d/1b1gK5ZTmNfCgFiAuNdZm8ljQHuMcaRLO/view?usp=sharing

I tried to bound the remote controller thrice before shutting off. However I'll do this other test in a bit.

**Comment by sburdix** [comment]
It's me again. Here you go. 
[latest.log](https://github.com/user-attachments/files/16881825/latest.log)

**Comment by SuperMartijn642** [comment]
![image](https://github.com/user-attachments/assets/a3c80b57-70d3-4ea3-968e-067938b17f2d)
It seems to be working correctly. When you right click on the elevator controller, it indeed updates the item nbt with the position of the controller, yet when trying to right-click the item later, its nbt is suddenly empty.
It would seem the item nbt is somehow reset after the right-click interaction with the controller.

Here is a file which makes a copy of the current held-item, edits the copy's nbt, then sets the held item to the copy, rather than just changing the nbt of the held item:
https://drive.google.com/file/d/1p6ZG6r1khTxwLwzfQ3hT5qQpkKEO3qhm/view?usp=sharing
I think some mod might be keeping track of the player's items and not noticing the the right-click interaction changed the nbt.
If this doesn't fix it however, I am afraid I am kinda out of ideas 😅

**Comment by sburdix** [comment]
> ![image](https://private-user-images.githubusercontent.com/12382965/364569744-a3c80b57-70d3-4ea3-968e-067938b17f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjgxMjQsIm5iZiI6MTcyNTUyNzgyNCwicGF0aCI6Ii8xMjM4Mjk2NS8zNjQ1Njk3NDQtYTNjODBiNTctNzBkMy00ZWEzLTk2OGUtMDY3OTM4YjE3ZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA5MTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYjcyZjY2NGZhODk4MTY5MGU1ZjNhYzNiNzViOGNkODU2ODhkNDEzZWE5NDUzMzY0MGQ3OWIyNzNiMGY2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d7eQBLJwiUi6QIAOxBbSGNJ2-KPcexQcnKR7HNlmXW0) It seems to be working correctly. When you right click on the elevator controller, it indeed updates the item nbt with the position of the controller, yet when trying to right-click the item later, its nbt is suddenly empty. It would seem the item nbt is somehow reset after the right-click interaction with the controller.
> 
> Here is a file which makes a copy of the current held-item, edits the copy's nbt, then sets the held item to the copy, rather than just changing the nbt of the held item: https://drive.google.com/file/d/1p6ZG6r1khTxwLwzfQ3hT5qQpkKEO3qhm/view?usp=sharing I think some mod might be keeping track of the player's items and not noticing the the right-click interaction changed the nbt. If this doesn't fix it however, I am afraid I am kinda out of ideas 😅

I tried, and it still doesn't work. I appreciate your help and patience, but let's stop. Keep up the good work tho, big fan.

**Comment by SuperMartijn642** [comment]
Yup then there's not much I can do about it. The block interaction properly sets the item nbt, yet at some point after that it is cleared. I don't have control over that and it'd have to be some other mod causing it 🤷‍♂️

Anyways, massive thanks for all the help! Too bad, we couldn't find a solution.
