### ISSUE TITLE
 [Bug] Famuflage missing texture

### ISSUE THREAD

**Issue by xdjzack** [SuperMartijn642/MovingElevators#236]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.4.8

**Are you using OptiFine?**: Yes, but I testet without

**Description of the Bug**
Famuflage missing texture on all the blocks

**Steps to Reproduce**
I have alot of mods, idk witch one is conflicting.

**Screenshots**
![123](https://github.com/user-attachments/assets/61958c14-6343-49f9-9515-01546a263c75)

Modlist
![modlist 1](https://github.com/user-attachments/assets/14f32520-402f-4c03-ad3d-3b89d769e721)
![modlist2](https://github.com/user-attachments/assets/679f4e01-b32c-4b3c-a4e9-690af8652934)

**Comment by SuperMartijn642** [comment]
Please narrow down the mods as well as the steps needed to reproduce the issue.

**Comment by xdjzack** [comment]
I've been trying to narrow it down, disabling some mods and testing. 
But there are so many mods, and sometimes I disable some mod so the modpack wont even start and it gives me error code 1.
What is easiest way to find the conflict? I'm about to give up

**Comment by SuperMartijn642** [comment]
Easiest is just to disable half the mods at a time (besides Moving Elevators ofc), then:
- If the issue persists, repeat with the mods still enabled
- If the issue goes away, repeat with the mods you just disabled

Eventually you will narrow it down to a small set of mods.
For a set of 200 mods, this would take 8 attempts until you are left with a single mod.

**Comment by xdjzack** [comment]
Steps to Reproduce
Having these mods installed
Moving elevators
ConnectedTexturesMod
CTM-MC1.12.2-1.0.2.31.jar

**Comment by xdjzack** [comment]
I fixed my issues I had with optifine, so I'm now using connected textures through that.
ConnectedTexturesMod was taken from the official Tekkit 2 modpack, why I was originally using it.
Thank you for the quick response :)

**Comment by SuperMartijn642** [comment]
The issue with ConnectedTexturesMod has been fixed now in Moving Elevators version 1.4.8a.
Thank you for reporting the issue!
