### ISSUE TITLE
[Feature] ...horizontal movement

### ISSUE THREAD

**Issue by Killeronduty1** [SuperMartijn642/MovingElevators#238]
Hey, what are your thoughts on possibly making your elevator have the ability to go horizontal? I really love this mod and would love to have the ability to make horizontal elevators. this could be done with either a completely new block or by integrating it into the present elevators.

**Comment by SuperMartijn642** [comment]
Seems like a duplicate of #89. Just not really something I am interested in and it would also require most of the internals to be redone.
