### ISSUE TITLE
[Feature] Blacklist / whitelist certain blocks to be part of cabinet

### ISSUE THREAD

**Issue by donmor** [SuperMartijn642/MovingElevators#239]
**Is your feature request related to a problem? Please describe.**
I don't want bedrocks or other unbreakable blocks got moved

**Describe the solution you'd like**
Add configurations to blacklist / whitelist certain blocks. Blacklist bedrocks and other unbreakable blocks by default.

**Comment by SuperMartijn642** [comment]
Unbreakable blocks already cannot be moved by the elevator.

**Comment by donmor** [comment]
Oh, okay :)

**Comment by donmor** [comment]
So what blocks can be moved right now? Does it move only solid blocks, or block entities as well? What do blocks that require attachment block do if moved? (e.g torches, redstone)

**Comment by SuperMartijn642** [comment]
The elevator will move any blocks which are not unbreakable including their block entities.

> What do blocks that require attachment block do if moved? (e.g torches, redstone)

Once the elevator arrives, all the blocks in the cabin will be updated. Blocks like torches and redstone will simply break and drop in item form like when the block they're placed on is broken.

**Comment by SuperMartijn642** [comment]
I will close the issue then, since I assume you no longer have a use case for your original request.
