### ISSUE TITLE
[Crash] Crashes when switching to a next page in creative inventory when sodium is installed

### ISSUE THREAD

**Issue by nickademas** [SuperMartijn642/MovingElevators#245]
**Version Info**
- Minecraft, 1.21.3
- Moving Elevators, 1.4.9
- Sodium (i tried both 0.6.0-beta.3 and the newest build from github actions)

**Are you using OptiFine?**:  no

**Steps to Reproduce**
1. Launch the game with sodium and moving elevators
2. Join a world in creative mode
3. Click this 
![image](https://github.com/user-attachments/assets/5a724d8e-6933-4122-ac10-c46b7a73ccf8)

**Crash report (~/logs/latest.log)**

[latest.log](https://github.com/user-attachments/files/17537490/latest.log)

**Comment by SuperMartijn642** [comment]
This appears to be an issue with Sodium and I have reported it here: https://github.com/CaffeineMC/sodium/issues/2849
I will close this issue as it appears to be unrelated to Moving Elevators. Still, thank you for reporting the issue of course!
