### ISSUE TITLE
[Feature] ... ko_kr update

### ISSUE THREAD

**Issue by park-cheolwoo** [SuperMartijn642/MovingElevators#248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- translation check : ✅
- Minecraft simulation with ko_kr.json adaption : ✅
- Transltion quailty : 4/5 (I wish it is 5/5) / Better then use only en_us.json 

[moving_ko_kr.json](https://github.com/user-attachments/files/17691989/moving_ko_kr.json)

**Comment by SuperMartijn642** [comment]
Thank you for the translations!

Could you create a pull request to add them? Simply go to [`src/main/resources/assets/movingelevators/lang`](https://github.com/SuperMartijn642/MovingElevators/tree/forge-1.15/src/main/resources/assets/movingelevators/lang) and press the 'Add file' -> 'Create new file' button in the top right. Then follow the steps GitHub provides.
![image](https://github.com/user-attachments/assets/e269f6f4-82b7-40c9-b39d-caf690ea367f)

With a pull request, it will show you were the one who created the translations and I can merge them easily.

**Comment by SuperMartijn642** [comment]
Files are all uploaded now, so the translations from #250 are available now in Moving Elevators version 1.4.10.
Again, thank you for the translations!
