### ISSUE TITLE
Compat w/ Double Slabs Mod

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/MovingElevators#25]
Minecraft v1.15.2

Currently [Double Slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs)  from that mod cannot be used.
Would this be possible to support?

**Comment by SuperMartijn642** [comment]
Do you mean support for camouflage, or does it not work as the elevator platform?

**Comment by WenXin20** [comment]
It doesn't work as a platform, although I hadn't tried the camouflage

**Comment by SuperMartijn642** [comment]
Oh ok, well camouflage shouldn't work as that only works with full blocks.
I will look into why it doesn't work with slabs, it is supposed to work if the top of the block space is solid, thus it should work when the top slab is there.

**Comment by WenXin20** [comment]
Maybe the Double Slabs mod has them as tile entities?

**Comment by SuperMartijn642** [comment]
Oh well then that would be the reason, currently I don't allow blocks with tile entities for the platform. I will probably change that in the future, but it will be a while before that happens.

**Comment by SuperMartijn642** [comment]
Yes, the slab blocks do indeed have tile entities.

> currently I don't allow blocks with tile entities for the platform. I will probably change that in the future, but it will be a while before that happens.
