### ISSUE TITLE
[Crash] Moving Elevators 1.4.10 - NeoForge 21.1.77 Render Crash on Elevator Use

### ISSUE THREAD

**Issue by Naphthy** [SuperMartijn642/MovingElevators#254]
Moving Elevators 1.4.10
Neoforge 21.1.77
MC 1.21.1

No Optifine

Steps to Reproduce:
1. Build elevator, in this instance 5x5x7 with two floors w/ floor displays, and a remote panel w/ floor display
2. press an elevator button
3. crash

Log containing crash in question:
[2024-11-16-7.log](https://github.com/user-attachments/files/17787813/2024-11-16-7.log)

**Comment by Naphthy** [comment]
I should add: 

Playing on self-hosted Server, Server does not show related errors.

**Comment by SuperMartijn642** [comment]
The error seems to occur inside a mixin from Sodium Extra. Could you check if the issue goes away when disabling that mod and if so, report the issue to them?
![image](https://github.com/user-attachments/assets/c8ff2e3e-b084-4edb-9d7a-6988a1e95910)

**Comment by Naphthy** [comment]
Alright disabling it solved the crash!

Ill report that to them, thanks.
