### ISSUE TITLE
[Crash] entity blocking elevator (?)

### ISSUE THREAD

**Issue by graveyardia** [SuperMartijn642/MovingElevators#256]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.10

**Are you using OptiFine?**: not that i know of, though "optifine support" is included in the error report.

**Steps to Reproduce** 

testing at the moment. this error occurred while constructing my elevator; specifically, after installing and testing a new remote controller on the second subterranean floor. there are three subterranean levels, and six above ground levels. all above ground levels worked fine with no errors/lag.

i think the issue may be when another entity is in the way of the elevator (perhaps specifically modded entities), as i got kicked off the platform when a rascal obstructed the cabin upon relaunching. the crash occurred on the same floor. after.....evicting.....the rascal, the crash could not be reproduced.

(i know absolutely nothing about code, thats just a guess lol. the error doesn't name the mod, however i have been building in this world with all existing mods sans elevator for over 100 hours.)

the...evicted...rascal was standing where my crosshairs are in the attached picture when the elevator was called.

![2024-11-18_01 18 36](https://github.com/user-attachments/assets/1a88ff52-6099-49fb-ad5a-87df27afa274)

**Crash report (~/logs/latest.log)**
my modpack is massive, so the report exceeds character limit. crash report is located here:
[crash-2024-11-18_00.54.32-client.txt](https://github.com/user-attachments/files/17797889/crash-2024-11-18_00.54.32-client.txt)

**Comment by SuperMartijn642** [comment]
The way things are rendered in Minecraft is that you request a buffer and then put the data from quads into that buffer. How that buffer is allocated or how it is handled in the background is up to Minecraft's system.

The crash occurs when Moving Elevators is submitting quads from blocks in the cabin to a requested buffer and during that the needed allocated space gets resized from 2145388032 to -2147482112, resulting in an error. Likely caused by some integer overflow somewhere.
This occurs outside the control of Moving Elevators and is likely caused by some other mod making changes to how vanilla's system works, introducing a bug somewhere.

You indeed seem to have a lot of mods loaded and there's no clear indication as to what mod would be causing the issue.
That being said, there are some mods which add mixins (changes to vanilla code) into the class which handles the buffers: Oculus, ImmediatelyFast, Entity Texture Features, Embeddium, and ModernFix.
These mods I think are most likely to be the ones leading to this issue.

I don't think there's much I can do at this point. If you are able to narrow down which mods are needed for the issue to occur or if you can figure out a way to reproduce the issue, the issue could be further investigated.
However, I can understand if there's no way to reliably reproduce the issue or if it is hard to narrow which mods are needed.

**Comment by graveyardia** [comment]
Thank you for taking the time to explain this! (Un)fortunately, the rascal has made a return to my elevator shaft, so I'll have more opportunities to reproduce the crash. I normally include those four as a base in my modpacks, so it's good to know they can act up when combined with other mods. Time to rework the base pack, I suppose!

I'll let you know if I find out what the issue is. :)

Love the mod and will be including it in future rotations!

**Comment by graveyardia** [comment]
So to troubleshoot, I spawned a handful of rascals in the shaft then traveled up and down. I was unable to reproduce the crash. However, I made some assumptions based on performance - at times, rather than crashing, the elevator would lag/the cabin would "break" (i.e. produce particles and the sound of breaking blocks, though the cabin remained undamaged). I'm _guessing_ that while it isn't quite an overflow, it is somewhat related to the issue. The effects sound similar to errors reported with OptiFine.

However, all four were disabled and the effects from moving through the cabin remained. While they may have contributed to the error, I assume they were not the root of the problem but caused the crash when combined with an additional mod(s).

I moved on to culling nonessential mods to see what, if anything, would improve performance. For context, this modpack is being used as a quest amongst friends to collect nearly all* possible biomes; the elevator mod is needed, as there are over 250 exhibits to fill within the exhibit hall. 

The following mods were removed, and the "breaking" was resolved (there is a small amount of lag between the main floor and the first subterranean floor, but noticeable improvement. could simply be related to rendering the massive structure and nearby underground biomes lol). 

Organized by performance related mods, then general (mostly) library mods:
-Neruina - Ticking Entity Fixer (bawnorton)
-ESF (traben_0)
-ETF (traben_0)
-EMF (traben_0)
-Athena (Codex Adrian)
-BadOptimizations (thosea)
-Controlling (Jaredlll08)
-Server Performance (someaddon)
-Polytone (MehVahdJukaar)
-Better Fps - Render Distance (someaddon)

-Forge CIT (tfarecnim), as well as its dependent, Bibliophilia Resource Pack (PareidoliaG)
-Euphoria Patches (SpacEagle17)
-Recipe Essentials (someaddon)
-Skin Layers 3D (tr7zw)
-Village Spawn Point (Serilum)
-Collective (Serilum)
-Persistent Inventory Search (Serilum)
-Bottled Air (Serilum)
-Berries & Cherries Delight (jmods)
-Tiny Skeletons (Fuzs)
-Mindful Darkness (Fuzs)
-Enchanting Infuser (Fuzs)
-[Let's Do] WilderNature (satisfy)
-New Slab Variants (Lupin)
-Better Villages (jtl_elisa)
-Boat Break Fix (ElocinDev)
-Catalogue (MrCrayfish)
-MrCrayfish's Furniture Mod Legacy (MrCrayfish)
-Clayworks (TeamAbnormals)
-Music Discs - Juice World (tatobyoii)
-Hearth & Home (Starfish_Studios)
-Another Furniture (Starfish_Studios)
-Naturalist (Starfish_Studios)
-Hibernal Herbs (DakotaPrideModding)
-Shanty Discs (AcewinTheGaming)
-Friends & Foes (Faboslav) RIP to the rascals who died for the cause.
-Plant Producer (TrueRealCursed_Warrior)

At the moment, I have another elevator to build as well as additional construction on the structure before the game starts, so I'll work on narrowing it down after I'm done!

*most, save for redundant biomes.

P.S. Had a funky little visual glitch after removing the mods, though it was easily fixed by slapping another walnut plank on the nonbutton side of the blocks lol. Not sure if this is indicative that whatever was conflicting is gone now, but it is interesting to note, especially since two of the floors were randomly reset? None of the mods containing the buildings' blocks were removed, nor were any other structures in/around the building affected. 

Additionally, as I was fixing the main blocks, I discovered the remote controllers were disguised as some kind of transparent plant block (they were walnut logs pre-cull). Only the Moving Elevator Blocks appear to have been impacted by the culling.

![2024-11-18_16 02 47](https://github.com/user-attachments/assets/9336ea45-ca4a-4677-9735-05b43d8f58d4)

**Comment by graveyardia** [comment]
Update: This crash occurred again while previewing the build via Discord with friends. It traced directly back to Embeddium/Oculus. I've left a Bug Report on Embeddium's page to make them aware that something with their mod causes this issue.

**Comment by graveyardia** [comment]
Coming back to this just in case anyone else has issues - I added MemorySweep to the modpack, and thus far havent had any crashes.
