### ISSUE TITLE
[Crash] Moving Elevator may conflict with REI and can't open creative tabs

### ISSUE THREAD

**Issue by Neyugndt** [SuperMartijn642/MovingElevators#257]
**Version Info: 1.21.3
- Minecraft Fabric
- Moving Elevators 1.4.10

**Are you using OptiFine?**: No

**Steps to Reproduce**
- Can't access crafting recipes through REI theme, the same will happen in creative
- Can't open mod's blocks through creative, if I force to open it will crash
**Crash report (~/logs/latest.log)**
[crash-2024-12-03_16.57.24-client.txt](https://github.com/user-attachments/files/18006741/crash-2024-12-03_16.57.24-client.txt)

**Comment by SuperMartijn642** [comment]
I cannot reproduce this. I can open creative tabs, look at recipes in REI, and interact with Moving Elevator's blocks fine with Moving Elevators and REI installed.

**Comment by Neyugndt** [comment]
I just figured it out, it was due to both iris and sodium mods

**Comment by SuperMartijn642** [comment]
Ah okay, what version of Sodium are you using?
There was a bug in Sodium where any item model using Fabric Rendering API would lead to a crash. If you are not using the latest version, could you try if updating that fixes the issue?

**Comment by Neyugndt** [comment]
I just updated it after realizing the problem. I forgot to update the latest version and still used beta. After removing and installing the latest version, I can use Elevator mod without crashing.

**Comment by Neyugndt** [comment]
Anyway thanks for your response
