### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by taleknight** [SuperMartijn642/MovingElevators#258]
**Version Info**
- Minecraft, Minecraft Forge 1.21.4-54.0.12
- Moving Elevators, 1.4.10

**Are you using OptiFine?**: No

**Steps to Reproduce**

Installing the mods:

- 'Moving Elevators 1.4.10 for Forge 1.21.4'
- 'SuperMartijn642's Config Library 1.1.8 for Forge 1.21'
- 'SuperMartijn642's Core Lib 1.1.17a for Forge 1.21.4'

Using Minecraft Forge in any versions of the version 1.21.4, for server. Starting it then causes a "Crash" with unexpected error like "for invalid dist DEDICATED_SERVER".

**Crash report (~/logs/latest.log)**

[latest.log](https://github.com/user-attachments/files/18247466/latest.log)

**Comment by SuperMartijn642** [comment]
It should be fixed now in Moving Elevators version 1.4.10a for Forge 1.21.4.
Thank you for reporting the issue!
