### ISSUE TITLE
Remote controller and comparators

### ISSUE THREAD

**Issue by AlexeyOplachko** [SuperMartijn642/MovingElevators#27]
It'd be quite useful to allow remote controller to also send comparator signal when elevator is on a floor tied that remote controller.

**Comment by SuperMartijn642** [comment]
Oh indeed, I completely forget about redstone. 🤦‍♂️

**Comment by SuperMartijn642** [comment]
Comparators will now work on remote elevator panels as well in Moving Elevators 1.3.0.

Thank you for reporting the issue!
