### ISSUE TITLE
i cant read the rightings with shaders

### ISSUE THREAD

**Issue by ZoruaBit** [SuperMartijn642/MovingElevators#28]
![image](https://user-images.githubusercontent.com/39221658/82734537-2759e980-9ce1-11ea-89ce-a26bc8dde098.png)

**Comment by SuperMartijn642** [comment]
What Minecraft, Forge and Optifine versions are you using?
What shader pack are you using?

**Comment by ZoruaBit** [comment]
forge verson is 31.2.0 and optifine is OptiFine 1.15.2 HD U G1 pre18 as thats the only 1.15 optiifne 

the shader pack is Sildurs Vibrant Shaders v1.27 Extreme

**Comment by ZoruaBit** [comment]
also its in dark light like under a roof or in a house

**Comment by SuperMartijn642** [comment]
Finally got around to fixing this. It is fixed now in 1.2.31a-mc1.15, 1.2.31a-mc1.16.1, 1.2.31a-mc1.16.2, 1.2.31a-mc1.16.3, and 1.2.31a-mc1.16.4.

Thanks for the reporting the issue!

**Comment by ZoruaBit** [comment]
thank you. ngl i completly forgot about this bug cause i have been playing minecraft without shaders lol
