### ISSUE TITLE
Question about Elevator Display

### ISSUE THREAD

**Issue by traveldesign** [SuperMartijn642/MovingElevators#33]
Love the mod. So if you look at the screenshots I attached, you can see that i'm using 2 display blocks so all 10 of my floors show. However, the displays cut off the very top or very bottom of my floors depending on what floor i'm on. If I'm at the very bottom, I can't see the top 2 floors on the display. And if I'm on the top floor, I can't see the very bottom 2 floors on the display. Is there any way you could change this? The display has so much unused space that it could use. Thanks!
![2020-07-31_14 44 43](https://user-images.githubusercontent.com/60497291/90171426-1b714700-dd67-11ea-9e28-454ad5228f4b.png)
![2020-07-31_14 40 25](https://user-images.githubusercontent.com/60497291/90171429-1c09dd80-dd67-11ea-8b95-bed0e93fc5bb.png)

**Comment by SuperMartijn642** [comment]
Right now I have it so the floor the display is on is in the center. I might change it so it centers all the floors which would allow for more floors to be displayed.
I will probably change it this week or next week, however I can't make any promises since I have to work a lot.

**Comment by traveldesign** [comment]
That would be awesome. I see the logic in centering the current floor though. No rush! I appreciate you replying so fast. Thanks for creating the mod!!

**Comment by SuperMartijn642** [comment]
I changed it now to be centered in version 1.2.20.

Thanks for the suggestion!

**Comment by traveldesign** [comment]
Awesome! You rock!
