### ISSUE TITLE
Crash on launch [1.16.2]

### ISSUE THREAD

**Issue by Sunekaer** [SuperMartijn642/MovingElevators#34]
Crash on launch due to missing license in Mods toml

like https://github.com/Sunekaer/Flat-Bedrock/blob/ec0351b6a3105a76c520cfb010a59f39de8fa5a2/src/main/resources/META-INF/mods.toml#L4

https://pst.ksun.io/ocutoxakas.sql

**Comment by SuperMartijn642** [comment]
Thanks, I fixed it now in version 1.2.19.
