### ISSUE TITLE
Floor display error

### ISSUE THREAD

**Issue by zy286** [SuperMartijn642/MovingElevators#35]
The version I use for minecraft is 1.16.1 and forge 32.0.108

I build a tower with 30 floors, I choose to let the elevator to stop at odd floors only. However, from 17th floor on, the display loses track of the lowest floors: i.e. for floors 1-15, I can see all the floors from 1,3,...,29; but on 17th floor I saw 3,5,...,29; on 19th I saw 5,7,...,29, etc. More importantly, for those floors with wrong display, I cannot reach the correct floor by clicking the display! If I click 3rd floor on 17th, I go back to 1st floor!!! Please solve this problem (and hope it won't need 1.16.2 as I don't want to update my server all over again)

Thank you very much!

**Comment by SuperMartijn642** [comment]
I believe this is the same issue as #36, which should be fixed now in version 1.2.21.

Thanks for the report!
