### ISSUE TITLE
Elevator Displays don't have enough room for many floors.

### ISSUE THREAD

**Issue by RavenholmZombie** [SuperMartijn642/MovingElevators#36]
I'm playing on Minecraft 1.12.2 with Moving Elevators 1.2.20-mc1.12

The Elevator Display blocks don't have enough space to display all of the floors in large buildings.
The most I am able to fit is Nine floors before the display starts cutting off lower floors, and there is no noticeable way of scrolling the list.

Screenshot: https://i.imgur.com/tPz1tI3.png

My building's main floor is labeled as Ground and is not visible on the list.

**Comment by SuperMartijn642** [comment]
I found the issue, it is fixed now in version 1.2.21.

Thanks for the report!
