### ISSUE TITLE
Block standing on disappears travelling up a number of levels on stop [Bug] ...

### ISSUE THREAD

**Issue by NuL1F3** [SuperMartijn642/MovingElevators#38]
**Version Info**
- Minecraft: 1.16.3
- Forge: 34.1.35
- Chunk Loaders, None

**Description of the Bug**
Since no one else seems to be having this issue I am sure it is my selection of mods causing the issue. Travelling upwards from level 10 to 60 (for example), more often than not the block your character is standing on disappears and you fall to your death.

**Steps to Reproduce**
Simply created an elevator as per instructions (have tried a number of different vanilla blocks) and ride.

**Comment by SuperMartijn642** [comment]
Sorry, Chunk Loaders should have been Moving Elevators. What version of Moving Elevators are you using?

What mod pack are you playing or if it is self made, could you share a screenshot of the list of mods?

**Comment by NuL1F3** [comment]
Moving Elevators: 1.2.26
![Forge 1 16 3 MODS](https://user-images.githubusercontent.com/32502949/99753062-4a027900-2b31-11eb-8d53-46f97e7ea5b6.JPG)
Thank you for your time :)

**Comment by SuperMartijn642** [comment]
I tested with the mods you have installed and it seems to work like normal. Maybe it has something to do with your setup.

When the elevator arrives, is one block from the platform not placed or do all the blocks get placed but just the player falls through.
What is one the blocks for the platform the issue happens with?

Also one of the packets to update the elevator position wasn't handled correctly in version 1.2.26. It is fixed now in version 1.2.27, maybe that fixes the problem.

**Comment by NuL1F3** [comment]
I will be sure to update!

When the elevator arrives, the block that has the entity on it simply disappears. Not everytime, just more often than not.

Thank you so much for spending your time to help me with this issue. I did fail to mention I am running a server, I'm not sure how much that changes anything?

As said, I will download the updated file and fingers crossed that is why I am having this issue. Thanks again 👍

**Comment by NuL1F3** [comment]
Hi, thank you again for your time, since updating, the platform no longer drops blocks :D

**Comment by SuperMartijn642** [comment]
I guess it was probably a syncing issue then, glad to hear the update fixes it.
