### ISSUE TITLE
forge 1.16.4 on world gen [Bug] ... Error executing task on Client java.lang.IndexOutOfBoundsException: readerIndex(5) + length(4) exceeds writerIndex(5)

### ISSUE THREAD

**Issue by SDUBZ** [SuperMartijn642/MovingElevators#39]
**Version Info**
- Minecraft, 1.16.4-35.0.17
movingelevators-1.2.26-mc1.16.4

**Description of the Bug**
Error executing task on Client
java.lang.IndexOutOfBoundsException: readerIndex(5) + length(4) exceeds writerIndex(5)

**Steps to Reproduce**
unsure

logs:
debug : https://gist.github.com/SDUBZ/f6977c1a22de43124e0c4b4089bab7e7

latest: https://gist.github.com/SDUBZ/5dcea0d03a327cefd1dafc92ea2bcc92

**Comment by SuperMartijn642** [comment]
I accidentally gave two packets the same index, causing the packet to be received by the wrong handler. It is fixed now in 1.2.27.

Thank you for reporting the issue!
