### ISSUE TITLE
Elevator Speed is to high

### ISSUE THREAD

**Issue by Titoo8899** [SuperMartijn642/MovingElevators#4]
Hi,
in 1.12.2 give it a problem with the Speed. I find the Platformspeed of the elevator of 0,1 to 0,2 to fast in 0,1 is the speed good but I find in 0,2 is it to fast the 1,0 is from speed okay. Can you the Platform speed a little bit slower make and so the differentiate smoother make in the 1.12.2 Version?

**Comment by SuperMartijn642** [comment]
I feel the current options (0.1,0.2...0.9,1.0) are sufficient and I for now this won't be changed.
