### ISSUE TITLE
[Bug] 11th floor bug

### ISSUE THREAD

**Issue by AlsoLicorice** [SuperMartijn642/MovingElevators#40]
**Version Info**
- Minecraft, 1.15.2
- Moving Elevators, 1.2.27

**Description of the Bug**
Whenever I place down the 11th floor button, the first floor dyes/names the second, the second dyes/names the third, etc. When you get to the 11th floor, it dyes/renames the first. The zeroth floor is somehow unaffected.
**Steps to Reproduce**
Build an elevator shaft with 11 floors.

**Screenshots**
https://imgur.com/a/LA6WyBs

**Comment by SuperMartijn642** [comment]
Apparently the floor names and colors where read in an incorrect order when they were sent to the client. It is fixed now in version 1.2.28.

Thank you for reporting the issue!
