### ISSUE TITLE
[REDSTONE CALLING] The ability to call elevators with redstone using a remote controller

### ISSUE THREAD

**Issue by Scwestbrook** [SuperMartijn642/MovingElevators#41]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Hi, I've been thinking about automatically calling elevators, and I think that you should have a feature where, if a controller/remote controller is powered, the elevator is called to that floor, so that I could call it with, I don't know, a pressure plate?

**Comment by SuperMartijn642** [comment]
That's already a thing. If you power the elevator controller (and I believe the remote one as well,) the platform will come to that controller.

**Comment by Scwestbrook** [comment]
Thanks! I didn't realize that.

**Comment by Scwestbrook** [comment]
Actually, I just realized that it doesn't work with the remote controller. Could you add that?

**Comment by SuperMartijn642** [comment]
I added it now in version 1.2.29.

**Comment by Scwestbrook** [comment]
Thanks!

**Comment by Scwestbrook** [comment]
Just so you know, the comparator doesn't work with the remote controller either, or is that fixed?

**Comment by SuperMartijn642** [comment]
That's requested in #30 and will be added in some future update as that will take a bit more work to implement.

**Comment by Scwestbrook** [comment]
OK
