### ISSUE TITLE
[DISGUISE ISSUE] Sea lanterns

### ISSUE THREAD

**Issue by Scwestbrook** [SuperMartijn642/MovingElevators#42]
**Version Info**
- Minecraft, 1.16.4
- Moving Elevators, ...

**Description of the Bug**
When the controller/remote controller is right-clicked with a sea lantern, it does not change to a sea lantern.

**Steps to Reproduce**
Right-click a controller with a sea lantern.
**Screenshots**
...

**Comment by SuperMartijn642** [comment]
I changed it so any block with the collision of a full block can now be used as camouflage in version 1.2.31.

Thanks for reporting the issue!
