### ISSUE TITLE
[Bug] ... No buttons on remote display, for other plays in multiplayer

### ISSUE THREAD

**Issue by TDderpy** [SuperMartijn642/MovingElevators#43]
**Version Info**
- Minecraft, ... 1.16.4 - FTB direwolf20 Pack
- Moving Elevators, ...

**Description of the Bug**
...
When another player palces down the remote display there are no buttons on it, for other players in multiplayer. 
Buttons show up if you break and replace the block but only for the person who placed the remote display. 

Just a visual bug, it works as intened otherwise. 

relogging makes the buttons show up

**Steps to Reproduce**

place down remote display, look at it from another account
...

**Screenshots**

before re-log

![image](https://user-images.githubusercontent.com/44139414/102801133-b8468f80-43ac-11eb-8514-fa74ad0e0c6d.png)

after re-log

![image](https://user-images.githubusercontent.com/44139414/102801334-fcd22b00-43ac-11eb-99bf-eca8f21d7196.png)

...

**Comment by SuperMartijn642** [comment]
It is fixed now in version 1.2.30.

Thanks for reporting the issue!
