### ISSUE TITLE
Not able to carry entities

### ISSUE THREAD

**Issue by SinzHyper** [SuperMartijn642/MovingElevators#44]
So I have a car mod (https://www.curseforge.com/minecraft/mc-mods/transport-simulator-official-vehicle-set) and I downloaded your mod since it claimed it could carry entities. I try to use this mod to drive the cars on the elevator and when the elevator moves then the car glitches through the floor when it goes down. when it goes up the elevator just goes through the car. Any way to make it work properly?

**Comment by SuperMartijn642** [comment]
The entities from Transport Simulator - Official Vehicle Set don't seem to interact with anything except blocks. Pistons and Shulkers don't collide with the entities, they go straight through just like the elevator.
Any calls to the entity to move it, set its position, or set its motion are also ignored.

Sadly there's nothing I can do here.
