### ISSUE TITLE
[Bug] Z-fighting

### ISSUE THREAD

**Issue by anquietas-sys** [SuperMartijn642/MovingElevators#45]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.2.27

**Description of the Bug**
Zfighting on all of the screens/ controllers
**Steps to Reproduce**
go far away from spawn and place the block
**Screenshots**

![image](https://user-images.githubusercontent.com/76923632/103491369-f13d2600-4de8-11eb-95f8-c38ee3efb8d6.png)
)

**Comment by SuperMartijn642** [comment]
Seems it's a 1.12 only thing, so I will have to look more into it.

**Comment by SuperMartijn642** [comment]
Apparently it was some issue with the old rendering system in 1.12 and 1.14. I fixed it now in 1.2.31a-mc1.12 and 1.2.31a-mc1.14.

Thanks for reporting the issue!
