### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by kanauru** [SuperMartijn642/MovingElevators#46]
**Version Info**
- Minecraft, 1.16.3
- Moving Elevators, ...-1.2.29

**Description of the Bug**
Several times my friends and I would fall through the elevator once reaching the chosen floor. We would have to keep riding it until it eventually stops dropping us.

**Steps to Reproduce**
Random

**Comment by SuperMartijn642** [comment]
Seems you opened 2 issues for this. #47
