### ISSUE TITLE
[Bug] Falling through elevator

### ISSUE THREAD

**Issue by kanauru** [SuperMartijn642/MovingElevators#47]
**Version Info**
- Minecraft, 1.16.3
- Moving Elevators, ...-1.2.29

**Description of the Bug**
Several times my friends and I would fall through the elevator once reaching the chosen floor. We would have to keep riding it until it eventually stops dropping us.

**Steps to Reproduce**
Random

**Comment by SuperMartijn642** [comment]
Just some questions to make it a bit easier for me to test:

Are you using a regular Forge server or something like SpongeForge or Magma?
Is there lag when the issue occurs?
Does the issue occur going both directions or only when going up or only when going down?

**Comment by kanauru** [comment]
Whoops sorry for the delay.

Regular forge server.
It can happen whether there's lag or not.
I've only had issues when going up, never down.

**Comment by SuperMartijn642** [comment]
I am not having any issues using the elevator. Are you using any other mods you think might have an influence on the elevator?

**Comment by SuperMartijn642** [comment]
I assume the issue resolved itself.
If not, feel free to comment and I will reopen the issue.
