### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by Chrisjohnson57387** [SuperMartijn642/MovingElevators#48]
Getting the error "Missing License Information" from movingelevators-1.2.31a-mc1.16.4

**Comment by SuperMartijn642** [comment]
The file does contain the the license attribute when I download it and it also works just fine when I launch Minecraft.
Are you sure you are using movingelevators-1.2.31a-mc1.16.4?
If so, could you see if updating Forge fixes the issue?

Is there anything special about your Forge installation you think could be causing this issue?

**Comment by SuperMartijn642** [comment]
Pretty sure it works just fine.
I'll reopen the issue if you can give me the information I asked for, without that I can't do anything.
