### ISSUE TITLE
high floors causing extreme fps issue

### ISSUE THREAD

**Issue by ink717** [SuperMartijn642/MovingElevators#49]
I've been using this elevator mod since last fall and everything worked great until this week. We build a couple of 25-40 stories tall buildings and the double elevator display simply can't fit these floors. after installing elevators between different floors and across all floors, the average fps in the city dropped from 70+ down to 10-20fps, which made the game unplayable and a couple of my server member feeling motion sickness due to low FPS. I can't find anything valuable from any debug or log. Eventually, by removing every single mod in each server backup world, we figured out is elevators causing the extreme lag on the client-side. However, on the server-side everything is normal. I can't simply determine whether it's just the issue with floor height or a combined issue with other mods. If you'd like me to supply any examples/trials, I'd like to. This mod has been an important part across cities on my server and now without it, it's quite problematic.

**Comment by SuperMartijn642** [comment]
I believe I haven't touched the code for rendering for elevator displays in a long time, and I have learned a lot about rendering while working on other mods. I will have a look at it.

Some questions:
Are the frame rate issues constant or just when the elevator is moving?
Are the elevator controllers and displays camouflaged?
Are the frame rate issues present when using only Moving Elevators?

**Comment by ink717** [comment]
The frame rate issue is constant, as long as the elevator complex is within the render distance the frame rate will drop. 
Because the floor is too much, only a portion of floors can be displayed, the rest of them will just not be shown until reaching a closer floor to it. However, when "requesting" an elevator from the 40th floor back to 1 floor, (long range request) the green dot will go out of the display box. 
I did more tests, gradually removing all other mods that require block rendering. Just confirmed that the Moving Elevators is the only one that creates a significant FPS drop. With or without optifine or shaders.

**Comment by SuperMartijn642** [comment]
What Minecraft version and Moving Elevators version are you using?

**Comment by ink717** [comment]
Minecraft 1.16.4, forge 35.1.37. According to a few other people’s report, it happened on earlier forge version of 1.16.4 as well. All using the newest published version of Moving Elevators, although I found this issue also present in a couple earlier versions.

**Comment by SuperMartijn642** [comment]
So I have looked into it a bit and the main problem seems to be rendering the text on the displays. I tested it with vanilla signs and they have the same problem.
I have changed it now so it only renders text on the display when its within 15 blocks.
I have also made a couple of other performance improvements and I'm now porting them to all the pre 1.16.4 versions.

I should have an update ready within an hour or so which hopefully improves frame rates.

**Comment by SuperMartijn642** [comment]
I added the improvements now in version 1.2.32.
Can you test it out to see if that improves things?

**Comment by ink717** [comment]
the issue is now gone, no significant change of fps within different distances or render a range of elevator complex. Thanks for such a fast response to the issue! If we discovered anything later, will keep updated. 
Thanks!

**Comment by SuperMartijn642** [comment]
Glad that fixed it! 🙂
