### ISSUE TITLE
[Feature] mineshaft workings

### ISSUE THREAD

**Issue by Pbus91** [SuperMartijn642/MovingElevators#50]
If possible can you make it so rails and carts won't break when in motion. This would allow for better use in mineshaft tunnels with more potential as well. Not sure how possible but would be wonderful. Thx

**Comment by SuperMartijn642** [comment]
Do you mean when you place rails on the elevator platform?

**Comment by Pbus91** [comment]
Yea. It may be in a later version and I don't know as im using 1.12

**Comment by AbacusOperator** [comment]
I second this, it would be nice if was possible to place rails onto platforms and they would move with platform, allowing minecart elevators. If author considers adding this feature into MC 1.16+ versions of the mod, please also include compatibility for rails from [Transport](https://www.curseforge.com/minecraft/mc-mods/transport) and [Useful Railroads](https://www.curseforge.com/minecraft/mc-mods/useful-railroads).

**Comment by SuperMartijn642** [comment]
You can now have full cabins and thus also place rails in them in Moving Elevators 1.3.0!
