### ISSUE TITLE
Multi-Part Blocks Placed Above or Below Elevator Blocks Causes Top or Bottom Face To Become Invisible & Disguise Prevention

### ISSUE THREAD

**Issue by Yourname942** [SuperMartijn642/MovingElevators#51]
**Version Info**
- Minecraft 1.16.4
- Forge 35.1.37
- Moving Elevators 1.2.32-mc1.16.5
- Integrated Crafting 1.0.11
- Integrated Dynamics 1.4.2
- Integrated Terminals 1.1.1
- Integrated Tunnels 1.6.16

**Description of the Bug**
Various multipart pieces from Integrated Dynamics, Crafting, Terminals, and Tunnels cause the top face of the Elevator Controller, Elevator Display, and Remote Elevator Panel to become invisible, as well as prevent them from being able to be disguised. I have not tested this next part, but: I can assume that Applied Energistics 2, pipes from Cyclic, or other smaller than 1x1 block parts to have the same issue. The same happens if placed below (ie bottom face becomes invisible, and then you are prevented from disguising the elevator blocks)

**Steps to Reproduce**
1. Place a elevator controller in front of player like normal, as well as a second floor (height of 2nd floor doesn't matter)
2. place any multi-part components directly above the Elevator Controller, Elevator Display, or Remote Elevator Panel:  
(such as wires, pipes, readers, exporters, displays, etc from Cyclic, Applied Energistics 2, Mekanism, Integrated Mod's stuff, etc)

**Screenshots**
![Screenshot (82)](https://user-images.githubusercontent.com/58750222/106808074-ecfa6780-6637-11eb-9152-9db830ab797c.png)

**Comment by SuperMartijn642** [comment]
It seems this is only an issue with Integrated Dynamics, other mods work fine.

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.2.33.

Thanks for reporting the issue!
