### ISSUE TITLE
[Feature] Remote Elevator controller redstone signal

### ISSUE THREAD

**Issue by JTAG7371** [SuperMartijn642/MovingElevators#52]
**Is your feature request related to a problem? Please describe.**
Its not a problem but i really need these to support redstone signals on the wireless controller.

**Describe the solution you'd like**
I am making a laboratory in a mod server im playing and i would really like the option to emit redstone from the wireless receiver. That way i can make doors automatically close and given i have very limited space i cant use comparators and redstone wire. I tried implementing it myself but i lack knowledge in redstone on 1.12.2.

If possible could you look into it today and see if you can implement a solution so i can update the server mod asap :)

**Comment by SuperMartijn642** [comment]
Same as #27.
I won't be adding it today.
I will add it when I have time and feel like doing so.
