### ISSUE TITLE
[Bug] Transparent moving blocks

### ISSUE THREAD

**Issue by Begnom** [SuperMartijn642/MovingElevators#54]
**Version Info**
- Minecraft, 1.16.5
- Moving Elevators, movingelevators-1.2.33-mc1.16.5

**Description of the Bug**
When using shaders like SEUS PTGI, the blocks taht are moving up and down are transparent.

**Steps to Reproduce**
Turn on Seus PTGI HRR 2/2.1

**Screenshots**
![2021-03-06_23 37 54](https://user-images.githubusercontent.com/76882765/110222772-fd229280-7ed4-11eb-9aa5-34c22d496578.png)

**Comment by DaBeepster** [comment]
Same, except mine are transparent even without shaders

**Comment by DaBeepster** [comment]
> Same, except mine are transparent even without shaders

Ok so, here's the funny thing, I just fixed mine. Turns out it was because my graphics were on fabulous... I don't know about yours though, since you can't use fabulous with shaders on. Sorry.

**Comment by SuperMartijn642** [comment]
Nearly all of Moving Elevators rendering has been redone in Moving Elevators 1.3.0. Please open a new issue if this still happens with Moving Elevators 1.3.0.
