### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Ssimen** [SuperMartijn642/MovingElevators#56]
**V1.12.2**
- Minecraft, ...java
- Moving Elevators, ...

**You can't bring the elevator if it's any biggger than 7 blocks wide because of the reach limit**
...

**Steps to Reproduce**
...

**https://gyazo.com/c14bd56a49a83484662ef0b5fd02775c**
...

**Comment by SuperMartijn642** [comment]
That doesn't seem like bug.
Also there's the remote elevator panel to access the controls at a distance.
I don't know what other solution you would want than the remote elevator panel.

**Comment by SuperMartijn642** [comment]
If there is another solution you would like, please comment here and I'll reopen the issue.
