### ISSUE TITLE
Possibility of allowing the elevator control block to be 2 blocks above an elevator

### ISSUE THREAD

**Issue by brisingraerowing** [SuperMartijn642/MovingElevators#6]
I would like to have the control block 2 blocks above the elevator platform (so that it's at eye height). Would that change be possible. It could be a config option (off by default) or even an option on the control block.

**Comment by SuperMartijn642** [comment]
In the next update I am adding a display block to go on top of the elevator block.
The display will have buttons with the floor names.
Because of this I won't change the controller offset.

**Comment by brisingraerowing** [comment]
Sounds good to me.
