### ISSUE TITLE
[render bug] [Chisel Compat] "morphing" isn't always working.

### ISSUE THREAD

**Issue by Bass2style** [SuperMartijn642/MovingElevators#62]
Hi,

i found a little rendering bug with Chisel. not tested more than that, because there is a ton of block, but it seems a common issue, affecting a lot of blocks.

**Version Info**
- Minecraft 1.16.5
- Moving Elevators 1.2.34
- Chisel Chisel 2.0.1 Alpha 4

**Description of the Bug**
when applying a block on the elevator to morph it, a lot of them make the elevator transparent, no texture is applied.

**Steps to Reproduce**
- place your elevators
- choose your prefered Chisel2 block
- and, you have a chance that the texture doesn't work.

it seems really random on wich block is working or not, in my vidéo bellow, a light blue concrete variant is working, but not the magenta one.

**Screenshots**
- YT vidéo : https://youtu.be/lrdTGvntYvQ

Have a nice day.

**Comment by SuperMartijn642** [comment]
Nearly all of Moving Elevators rendering has been redone in Moving Elevators 1.3.0. Please open a new issue if this still happens with Moving Elevators 1.3.0.
