### ISSUE TITLE
[Feature] Even-numbered elevator sizes

### ISSUE THREAD

**Issue by AngleWyrm10** [SuperMartijn642/MovingElevators#63]
Allow for elevator sizes of 2x2, 4x4, ...

Reason:
1x1 is hard to work with, and 3x3 is larger than I need

**Comment by MakeGamer** [comment]
Yep. I built a whole tower that is even. Now my elevator looks stupid.

**Comment by ghost** [comment]
> Yep. I built a whole tower that is even. Now my elevator looks stupid.

Same here, I'd love for this.

**Comment by SuperMartijn642** [comment]
You can now have even-numbered sizes in Moving Elevators 1.3.0!
