### ISSUE TITLE
[Crash] 1.17.1 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by HonestAngel** [SuperMartijn642/MovingElevators#64]
**Version Info**
- Minecraft, 1.17.1
- Moving Elevators, movingelevators-1.2.34-mc1.17.jar
- forge-1.17.1-37.0.9-universal.jar

**Steps to Reproduce**
Just try to load the mods... Crashes on startup... java.lang.ExceptionInInitializerError: Null

**Crash report (~/logs/latest.log)**
[crash-2021-07-25_22.49.28-fml.txt](https://github.com/SuperMartijn642/MovingElevators/files/6875931/crash-2021-07-25_22.49.28-fml.txt)

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.2.34b for Minecraft 1.17.

Thank you for reporting the issue!
