### ISSUE TITLE
[Crash] Game won't load

### ISSUE THREAD

**Issue by KrolMC** [SuperMartijn642/MovingElevators#65]
Hello,
When added Moving Elevators mod game won't load with message: "Moving Elevators (movingelevators) has failed to load correctly java.langExceptionInInitializerError: null"
**Version Info**
- Minecraft: 1.17.1
- Moving Elevators: 1.2.34

**Crash report (~/logs/latest.log)**
[crash-2021-07-26_08.25.32-fml.txt](https://github.com/SuperMartijn642/MovingElevators/files/6876087/crash-2021-07-26_08.25.32-fml.txt)
[latest.log](https://github.com/SuperMartijn642/MovingElevators/files/6876090/latest.log)

**Comment by SuperMartijn642** [comment]
Duplicate of #64
