### ISSUE TITLE
[Crash] ... Fails to load

### ISSUE THREAD

**Issue by Phoenix830** [SuperMartijn642/MovingElevators#66]
**movingelevators-1.2.34a-mc1.17** & **movingelevators-1.2.34-mc1.17**
- Minecraft 1.17.1
- 37.0.32 Forge
- Moving Elevators, ...
[crash-2021-08-11_20.40.28-fml.txt](https://github.com/SuperMartijn642/MovingElevators/files/6971040/crash-2021-08-11_20.40.28-fml.txt)

**Steps to Reproduce**

Place mod in mods folder and launch
...
Prevent launch with the following errors

java.lang.NoClassDefFoundError: net/minecraftforge/common/ToolType

java.lang.NullPointerException: null
[crash-2021-08-11_20.40.28-fml.txt](https://github.com/SuperMartijn642/MovingElevators/files/6971037/crash-2021-08-11_20.40.28-fml.txt)

**Crash report (~/logs/latest.log)**
...

**Comment by SuperMartijn642** [comment]
Ah that's something that got removed in Forge 37.0.31.

For now, downgrading to Forge 37.0.30 or earlier would work. Until I fix it at least.

**Comment by Phoenix830** [comment]
Thank you for the quick response. That has got it to load.
