### ISSUE TITLE
[Feature] Hide Elevator Controller

### ISSUE THREAD

**Issue by ExDomino** [SuperMartijn642/MovingElevators#68]
Hello,

I would like to ask, or if this is not existing, suggest a way to hide the elevator controller completely if an elevator display is in place. Maybe in its interface for example. The block should be render cliend-side as the block used to hide it, in order to prevent any light glitches.

Thank in advance!

**Comment by SuperMartijn642** [comment]
You can now hide the buttons on the elevator controller in Moving Elevators 1.3.0.

Thank you for the suggestion!
