### ISSUE TITLE
[Question] It is possible to control the elevator via ComputerCraft and hide their Controllers ?

### ISSUE THREAD

**Issue by ExDomino** [SuperMartijn642/MovingElevators#69]
Hello,

I plan to create an elevator entierley controlled by ComputerCraft. I'm wonthering if a ComputerCraft computer can control the elevator and if so, if there is a way to completely hide/disable the controllers of the elevator to prevent it to be controlled by hand.

Thank in advance!

**Comment by SuperMartijn642** [comment]
Whoops, I didn't notice this was a question and not a feature request 😅 Sorry for the wait.

There's no ComputerCraft integration and I currently have no plans to add it. I'm not against it, but it would be yet another dependency in my workspace for which I have to update if it updates.
Maybe once I get Moving Elevators somewhat feature complete I will look into it. Feel free to create a feature request though, so at least I have a reminder.
