### ISSUE TITLE
[1.12.2] Sync players better to the elevators somehow

### ISSUE THREAD

**Issue by fkrisi11** [SuperMartijn642/MovingElevators#7]
Hy there,

So I've been using this mod for a few days now on my server.
There are sometimes lags on the server.
When the server is lagging and the elevator arrives, the player falls through the elevator.

This is understandable, but can something be done about this?

**Comment by fkrisi11** [comment]
Maybe a way to fix this would be to add a way for elevators to "hold the player" above the block until the elevator fully arrived and the block got placed back in the world.

**Comment by SuperMartijn642** [comment]
I changed it to update the position once more server-side after the platform stopped.
This might fix the problem, but I'm not 100% sure since I don't really have a way to simulate lag.

If it doesn't work with version 1.2.1 please let me know

**Comment by fkrisi11** [comment]
The update works really well. I have not fallen through a single elevator since the update. Thank you :)

**Comment by SuperMartijn642** [comment]
Yay, thanks for the report
