### ISSUE TITLE
[Crash] Crash on startup with newer 1.17 Forge versions

### ISSUE THREAD

**Issue by PhilipIONO** [SuperMartijn642/MovingElevators#70]
**Version Info**
- Minecraft,1.17.1 ...
- Moving Elevators, ...

**Description of the Bug**
... I have no idea what is happening but it keeps giving me this error for any 1.17.1 versions,  nothing else is in the mods folder.

**Steps to Reproduce**
...

**Screenshots**
...
![Minecraft_ 1 17 1 9_4_2021 11_28_36 AM](https://user-images.githubusercontent.com/90103766/132099887-cf5b573e-65d1-48ac-8fc1-9bf1403cba1d.png)

**Comment by SuperMartijn642** [comment]
Forge 37.0.31 had a breaking change. I am in the midst of a large update for Moving Elevators, thus I haven't been able to update it for the newer Forge versions.
For now, you can either use Forge 37.0.30 or lower, or wait for the update 🙂 (although the update might take a bit)

**Comment by SuperMartijn642** [comment]
I fixed it now in Moving Elevators 1.0.34b for Minecraft 1.17.

Thank you for reporting the issue!
