### ISSUE TITLE
[Crash] Crash on startup with 1.17.1 Forge version

### ISSUE THREAD

**Issue by Isn0l** [SuperMartijn642/MovingElevators#71]
**Version Info**
- Minecraft, 1.17.1
- Moving Elevators

**Screenshots**
![Crash Screenshot](https://user-images.githubusercontent.com/91086860/134049523-7b12df0b-d78c-4ae4-80c4-31f807b390f0.png)

**Comment by Isn0l** [comment]
> **Version Info**
> 
> * Minecraft, 1.17.1
> * Moving Elevators
> 
> **Screenshots**
![image](https://user-images.githubusercontent.com/91086860/134050396-45866b70-0eb1-405c-bb60-685a63f627f0.png)

**Comment by SuperMartijn642** [comment]
Same as #70
