### ISSUE TITLE
[Bug] Camouflage isn't working

### ISSUE THREAD

**Issue by Novai91** [SuperMartijn642/MovingElevators#73]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.2.33

**Description of the Bug**
When using a modded block as the control panel texture, the panel turns invisible, it can be reset to the base texture.

**Comment by SuperMartijn642** [comment]
What blocks are not working? All blocks from a certain mod for example or a specific set of blocks?

This might also be the same as #62 if it's blocks from Chisel.
