### ISSUE TITLE
[Bug] Failed To Load Mods

### ISSUE THREAD

**Issue by MarvellJayden1205** [SuperMartijn642/MovingElevators#75]
**Version Info**
- Minecraft, 1.17.1
- Moving Elevators, 1.2.34a

**Description of the Bug**
I can't load it because it was error, because forge said that this mod failed to load because error event phase.

**Steps to Reproduce**
None

**Screenshots**
None

**Comment by SuperMartijn642** [comment]
Can you send the `latest.log` file? Without that I can't help you.

What Forge version are you using? This probably the same as #70 if you're using a version higher than 37.0.30.

**Comment by MarvellJayden1205** [comment]
[2021-11-02-5.log.gz](https://github.com/SuperMartijn642/MovingElevators/files/7464887/2021-11-02-5.log.gz)

**Comment by MarvellJayden1205** [comment]
I am using Forge Version 37.0.103

**Comment by SuperMartijn642** [comment]
> I am using Forge Version 37.0.103

Well, then it's the same as #70.
