### ISSUE TITLE
[Bug] Redstone Signal to Controller Does Nothing

### ISSUE THREAD

**Issue by BTRBT** [SuperMartijn642/MovingElevators#77]
**Version Info**
- Minecraft 1.12.2
- Moving Elevators 1.2.34

**Description of the Bug**
Applying redstone signal to controller doesn't call the elevator to that floor.

**Steps to Reproduce**
Apply a redstone signal to controller. Observe immobility of elevator.

**Comment by SuperMartijn642** [comment]
It works again now in Moving Elevators 1.3.0.

Thank you for reporting the issue!
