### ISSUE TITLE
[Feature] Integration with Create

### ISSUE THREAD

**Issue by ZAKsPop** [SuperMartijn642/MovingElevators#78]
It would be awesome if you could integrate your mod with the create mod. Your controllers with Creates mechanics.

**Comment by SuperMartijn642** [comment]
What would you want the controller to do together with Create?

**Comment by ZAKsPop** [comment]
Well, Create can make some cool elevators with either the mechanical piston or the rope pulley. However it is difficult to make one that supports more than 2 floors. It would be nice to build a Create elevator and have elevator controls that supports multiple floors. Your controls would be sweet.

**Comment by SuperMartijn642** [comment]
I will not be adding such compatibility with Create. You can now have full elevator cabins in Moving Elevators 1.3.0, thus I don't see much benefit in using Create's contraptions.
Additionally, it would also be way too complex code-wise to make elevator controllers sometimes move elevator cabins and sometimes move Create contraptions just to be able to move Create contraptions up and down.
