### ISSUE TITLE
[Bug] Invisible platform when using fabulous graphics

### ISSUE THREAD

**Issue by King-Of-Knights** [SuperMartijn642/MovingElevators#79]
**Version Info**
- Minecraft, 1.17.1
- Moving Elevators, movingelevators-1.2.34b-mc1.17

**Description of the Bug**
... The missing elevator ground when the platform is moving

**Steps to Reproduce**
... As is in Screenshots

**Screenshots**
Scene:
![ ](https://media.giphy.com/media/HEcGs9jsOvCloefpjk/giphy-downsized-large.gif)

My Mods:
![](https://blog.tonytuya.top/screen.png)

**Comment by SuperMartijn642** [comment]
As we have discussed on discord, this seems to be due to the **fabulous** graphics setting.

**Comment by SuperMartijn642** [comment]
I fixed it now in Moving Elevators 1.2.34c for 1.17.

Thank you for reporting the issue!
