### ISSUE TITLE
[Bug] Elevator Controllers forget about their floor names and style

### ISSUE THREAD

**Issue by DevPGSV** [SuperMartijn642/MovingElevators#80]
**Version Info**
- Minecraft: 1.18.1
- Moving Elevators: 1.2.34-mc1.18

**Description of the Bug**
Elevator controllers forget about their names and "style" (when hidden as a different block).

**Steps to Reproduce**
Place some Elevator Controllers, give names to the floors and/or right click them with a block to change their style. 
After some time, the names of the floor go back to the default "Floor [number]" and their style goes back to the default grey.
I am not sure exactly when this happens, I haven't been able to find a pattern. Once I do, I'll update this issue.

**Comment by SuperMartijn642** [comment]
Ah I already know what the issue is. I fixed it in my core library, but I forgot Moving Elevators doesn't use my core library yet 🤦‍♂️
Should be an easy fix though luckily.

**Comment by SuperMartijn642** [comment]
I fixed it now in Moving Elevators version 1.2.34a for 1.18.

Thank you for reporting the issue!
