### ISSUE TITLE
[Bug] Mip Level 0

### ISSUE THREAD

**Issue by itsdinkd** [SuperMartijn642/MovingElevators#82]
[22:34:26] [Worker-Main-10/WARN]: Texture movingelevators:blocks/buttons with size 23x23 limits mip level from 4 to 0

latest 1.18 mod

**Comment by SuperMartijn642** [comment]
Minecraft tries to generate mipmaps for all textures, however only texture that are a power of 2 in size will work.
The texture it shows the warning for is the button texture for the elevator controller. I don't think it's very important to have those textures mipmapped as they are not used frequently anyways.

I will have to see if I want to change my code just to make that warning go away.

**Comment by itsdinkd** [comment]
Ohhh so it only sets the mipmap level for THAT texture, and not in general? That makes much more sense. Apologies for the useless report. ddddddddd   From: SuperMartijn642Sent: Sunday, December 12, 2021 5:07 AMTo: SuperMartijn642/MovingElevatorsCc: red2blue; AuthorSubject: Re: [SuperMartijn642/MovingElevators] [Bug] Mip Level 0 (Issue #82) Minecraft tries to generate mipmaps for all textures, however only texture that are a power of 2 in size will work.The texture it shows the warning for is the button texture for the elevator controller. I don't think it's very important to have those textures mipmapped as they are not used frequently anyways.I will have to see if I want to change my code just to make that warning go away.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SuperMartijn642** [comment]
I changed the texture to be 32 by 32 now in Moving Elevators 1.3.0.

Thank you for reporting the issue!
