### ISSUE TITLE
[Question] Black screen when elevator is moving

### ISSUE THREAD

**Issue by fistidgious** [SuperMartijn642/MovingElevators#83]
**Question**
...
Not sure if this is an issue but just downloaded latest 1.18.1 version first time use this mod so when i press the button i dont get ant moving animation like in the video just a black screen then a ding and hey ho i at the next floor !!!

**Comment by SuperMartijn642** [comment]
Are you using OptiFine?

**Comment by SrPeterr** [comment]
Having the same issue, disabling optifine worked, si there a solution for this? 😢

**Comment by SuperMartijn642** [comment]
Nothing I can do about it.
It works fine without OptiFine. OptiFine changes something that makes it not work. OptiFine is closed source, thus I can't know what it changes.

**Comment by SuperMartijn642** [comment]
Nearly all of Moving Elevators rendering has been redone in Moving Elevators 1.3.0. Please open a new issue if this still happens with Moving Elevators 1.3.0.
