### ISSUE TITLE
[Bug] Textures look odd when using OptiFine

### ISSUE THREAD

**Issue by johnsoul777** [SuperMartijn642/MovingElevators#84]
**Version Info**
- Minecraft 1.18.1, Forge 39.0.19, OptiFine_1.18.1_HD_U_H4
- Moving Elevators 1.2.34a-mc1.18

**Description of the Bug**
... Textures with shaders are not displaying correctly

**Steps to Reproduce**
... Install Sildur's Vibrant shaders v1.32 Extreme and play the game

**Screenshots**
...

![image](https://user-images.githubusercontent.com/72218928/149213933-09861a01-b50e-4da3-a620-dd7968cbc4d2.png)
![image](https://user-images.githubusercontent.com/72218928/149214062-d1932cd5-77f3-4ca0-ac55-e35f9c2616ae.png)
![image](https://user-images.githubusercontent.com/72218928/149215020-f55a5a73-6e99-4573-ba1c-958a0d6c615e.png)
![image](https://user-images.githubusercontent.com/72218928/149215922-3af5b63f-7aec-4730-874b-a73306797563.png)

**Comment by SuperMartijn642** [comment]
Nearly all of Moving Elevators rendering has been redone in Moving Elevators 1.3.0. Please open a new issue if this still happens with Moving Elevators 1.3.0.
