### ISSUE TITLE
[Bug] Rendering issues when using shaders

### ISSUE THREAD

**Issue by F0x06** [SuperMartijn642/MovingElevators#85]
Hi, i don't know if the bug is shader-specific and related to https://github.com/SuperMartijn642/MovingElevators/issues/84

**Version Info**
- Minecraft: 1.16.5, Forge: 36.2.23, Optifine: 1.16.5_HD_U_G8
- Moving Elevators: 1.2.34-mc1.16.5
- Shader: AstraLex (BSL Edit) By LexBoosT

**Description of the Bug**
Elevator controller and display renders wrongly

**Steps to Reproduce**
Enable Shader: `AstraLex (BSL Edit) By LexBoosT` 

**Screenshots**
![image](https://user-images.githubusercontent.com/7167311/149764075-7943b571-66be-4ec2-86ec-c5d9106e3e78.png)

**Comment by F0x06** [comment]
Managed to solve the issue by changing  `Shader Options`

`Shader Options` -> `Visual` -> `Advanced Materials` -> `Parallax` -> `Parallax Occlusion Mapping` -> `OFF`

I don't know if the issue is related to the mod itself, i let you close the issue if this is shader-related only

**Comment by SuperMartijn642** [comment]
Nearly all of Moving Elevators rendering has been redone in Moving Elevators 1.3.0. Please open a new issue if this still happens with Moving Elevators 1.3.0.
