### ISSUE TITLE
[Bug] Detection as malware from multiple providers.

### ISSUE THREAD

**Issue by tripartist1** [SuperMartijn642/MovingElevators#86]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.2.34

Detection as malware on latest Avast update.
...

Install latest version of Avast, try to run the mod on MC.
...

3 different providers are flagging the mod as malware on Virus Total. Not sure what in this version could be causing the issue, but it's the only mod which seems to have any problem so far out of hundreds. Previous version of the mod is fine.

**Comment by SuperMartijn642** [comment]
Did you download Moving Elevators from CurseForge or from another website?
