### ISSUE TITLE
3D elevator sizes

### ISSUE THREAD

**Issue by Craftingcat99** [SuperMartijn642/MovingElevators#87]
3D sizes for the elvator would be nice, so you could, for example, build some sort of cabin. A second slider for the vertical size, similar to the horizontal size, in the elevator controller would be perfect.  Then you could for example choose from 4; 6; 8: 10 blocks in height (4 being the minimum because: BLOCK, AIR, AIR, BLOCK, so that the player fits inside the cabin.

**Comment by SuperMartijn642** [comment]
I am working on a cabin instead just a platform for the next update. Pretty much everything for the cabin is done, including proper collision while it's moving. The main thing left to do is the ui to change the cabin size and movement speed.

**Comment by SuperMartijn642** [comment]
You can now have 3d elevator sized in Moving Elevators 1.3.0!
