### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by Conutik** [SuperMartijn642/MovingElevators#88]
**Version Info**
- Minecraft, 1.12
- Moving Elevators, movingelevators-1.2.34-mc1.12.jar  

**Steps to Reproduce**
Log into a server with the mod have optifine installed

**Crash report (~/logs/latest.log)**
[crash-2022-02-01_18.04.39-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/7989459/crash-2022-02-01_18.04.39-client.txt)

**Comment by SuperMartijn642** [comment]
Should be fixed now in Moving Elevators 1.3.0.

Thank you for reporting the issue!
