### ISSUE TITLE
[1.12.2] Texture problems

### ISSUE THREAD

**Issue by fkrisi11** [SuperMartijn642/MovingElevators#9]
Elevator component textures flicker if you apply a custom texture to them.
I'm using Optifine. I don't know if that changes anything.
Isn't this an overlapping texture problem?

![flicker](https://user-images.githubusercontent.com/26310365/79031022-6ce0ae00-7b9c-11ea-9681-b73e168329cc.jpg)

Sometimes the flickering stops and the elevator components look nice, but if you shift rightclick with an empty hand on these components, they have a transparent texture applied to them.

![flicker2](https://user-images.githubusercontent.com/26310365/79031089-db257080-7b9c-11ea-9c92-e61db4b8182b.jpg)

**Comment by fkrisi11** [comment]
New finding: If a texture is transparent and then you send the elevator somewhere, then it gets back the original, default texture. So that fixes it.

Placing a block next to these blocks with transparent textures, also fixes the texture of them.

**Comment by SuperMartijn642** [comment]
Are you using the latest version, 1.2.2? Because I thought I fixed that

**Comment by fkrisi11** [comment]
Yes, I am using the latest version

**Comment by SuperMartijn642** [comment]
Oh nevermind, it definitly shouldn't be completely invisible. Does that invisible block also have the factory block as disguise?

**Comment by fkrisi11** [comment]
The invisible block had that very same disguise.
Oh and.. this also happens with controller blocks as well

**Comment by SuperMartijn642** [comment]
Yeah the disguise is handled the same for the controller and display.
I will have a look at it tomorrow as it's 2 am for me right now 😁

**Comment by fkrisi11** [comment]
Yeah, it's 3am here as well.
I'm just pushing a hotfix for my modpack, so I ran into this.
Thank you in advance ^^

**Comment by Titoo8899** [comment]
Hi, the same Problem have I with the Elevator Block. Show Pictures!!!
The hide with other Block on the Elevator looks good and the Fix of Version 1.2.2 have work. Only by the Elevator Display have we the Problem with the loot of the Block. Show Picture!!!
Then I clear the Elevator Block Texture of a Gras Block to the Normal Elevator Block Texture this Problem have I also. Show Picture!!!

![2020-04-11_10 50 29](https://user-images.githubusercontent.com/42325138/79039714-822cfb00-7be3-11ea-835a-6cb552548871.png)
![2020-04-11_10 50 37](https://user-images.githubusercontent.com/42325138/79039716-82c59180-7be3-11ea-96ac-2b0221052558.png)
![2020-04-11_10 50 53](https://user-images.githubusercontent.com/42325138/79039717-835e2800-7be3-11ea-8ebf-ea36d2056a20.png)

**Comment by SuperMartijn642** [comment]
Both the invisible blocks and z fighting should be fixed in version 1.2.3.
The block is now only rendered through the tile entity renderer and the block itself now has no model.
