### ISSUE TITLE
[Feature] Elevator sizes

### ISSUE THREAD

**Issue by LidorPrototype** [SuperMartijn642/MovingElevators#90]
This is a basic feature request upon an existing one, which is bigger elevator sizes (currently I saw the max is 9X9, but it's still not enough for my current plan), a bigger platform will help a lot in the long run.

**Comment by SuperMartijn642** [comment]
The default values will actually be decreased to 7x7 in the next update, since I am also adding a height to it. However, you will be able to increase the size in the config.

**Comment by LidorPrototype** [comment]
How can one access the config? and change that? is it possible already?

**Comment by SuperMartijn642** [comment]
It will be available in the next update. There's currently no way to change the max platform size.
