### ISSUE TITLE
[Feature] Elevators Carry Blocks

### ISSUE THREAD

**Issue by LidorPrototype** [SuperMartijn642/MovingElevators#91]
It will be a great feature if we could place blocks and stuff on top of the elevator platform (not entities) and that the elevator will take them with it.
I know it's currently ignoring it b/c it's too much blocks to check, but a simple size will be enough for example lets take an example with the current max:
9X9 platform
the added will be lets say max of 4 block high and a ceiling for it, it will give a way better elevator sensation to this mod.

**Comment by SuperMartijn642** [comment]
The next update will have a cabin instead of just a platform.

Duplicate of #87.

**Comment by LidorPrototype** [comment]
It will have an option for a cabin (3D like the other issue) and a flat platform?

**Comment by SuperMartijn642** [comment]
You will be able to separately adjust width, depth, height and offset.
