### ISSUE TITLE
Crash server 1.12.2

### ISSUE THREAD

**Issue by SeagalKru** [SuperMartijn642/MovingElevators#92]
(Google translation from Russian)
Updated your mod to the latest version with the addition of an additional 2 mods (supermartijn642configlib-1.0.9-mc1.12.jar and supermartijn642corelib-1.0.16a-mc1.12.jar) and the server crashes, does not start. But the client starts without problems.
Something is wrong. Fix it please!
Thanks to!
[crash-2022-02-18_15.02.04-server.txt](https://github.com/SuperMartijn642/MovingElevators/files/8096980/crash-2022-02-18_15.02.04-server.txt)

**Comment by SuperMartijn642** [comment]
I fixed it now in Moving Elevators 1.3.1.

Thank you for reporting the issue!
