### ISSUE TITLE
[Crash] client 1.12.2 ...

### ISSUE THREAD

**Issue by SeagalKru** [SuperMartijn642/MovingElevators#94]
(Translated from Google from Russian)
The server is up. But now the client crash!
No comment! :-)
[crash-2022-02-18_20.08.45-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/8099119/crash-2022-02-18_20.08.45-client.txt)

**Comment by SuperMartijn642** [comment]
Great 🤦‍♂️
I tested it on 1.16 and the same code worked all the way down to 1.12, so I just assumed it would be fine 😅

**Comment by Titoo8899** [comment]
I think the crash of SeagalKru is the same as mine

**Comment by SeagalKru** [comment]
Well, in any case, we are waiting for repairs! ;-)

**Comment by SuperMartijn642** [comment]
I fixed the issue now in Moving Elevators 1.3.2.

Thank you for reporting the issue!
