### ISSUE TITLE
[Bug] Elevator was invisible in the newest Version 1.3.2 for 1.12.2 then we will up or down drive

### ISSUE THREAD

**Issue by Titoo8899** [SuperMartijn642/MovingElevators#97]
**Version Info**
- Minecraft Forge 14.23.5.2860 (newest Version of Minecrafts Forge)
- movingelevators-1.3.2-mc1.12 (newest Version who you the crash of Start Up have fix)

**Description of the Bug**
The Elevator build work but then we will up or down make the elevator was invisible in the first time of go up or down and was only visible then he have stop the tour. I have a video make of this

Link: https://www.youtube.com/watch?v=6cJ5_RSCPfk

**Steps to Reproduce**
Only make a Elevator and drive with it and the Person will by the 1 Floor to 3 Floor only of the earth land and then you Drive from 3 Floor to 1 Floor then fall you only 3 Floors down and then it is to high then death you.

**Screenshots**
![2022-02-19_21 00 51](https://user-images.githubusercontent.com/42325138/154817371-a1a8feeb-4e76-4fd2-9ea6-5d05820f1e2c.png)
![2022-02-19_21 00 03](https://user-images.githubusercontent.com/42325138/154817370-2797d7e7-9e7e-41ce-8774-edf393692615.png)

**Comment by Titoo8899** [comment]
the First Picture show my Elevator on 3 Floor and the Second Picture look my elevator then he go down to the 1 Floor and what see you nothing. The elevator was only visible then he have end of the tour from one to the other floor

**Comment by SuperMartijn642** [comment]
Are you using other mods? For example OptiFine?

**Comment by Titoo8899** [comment]
1- movingelevators-1.3.2-mc1.12
2- FishingMadeBetter-1.12.2-2.2.2
3- ElytraBombing-Forge-1.12.2-1.0.0
4- CDM-v1.12.2-1.1.00 (CDM = Cities Deco Mod)
5- Fexcraft+Common+Library-1.12.71 (I have the long name write but on Curse is the name FCL)
6- supermartijn642corelib-1.0.16a-mc1.12
7- supermartijn642configlib-1.0.9-mc1.12

Links to the Mod
2: https://www.curseforge.com/minecraft/mc-mods/fishing-made-bette
3: https://www.curseforge.com/minecraft/mc-mods/elytra-bombing
4: https://www.curseforge.com/minecraft/mc-mods/saracalias-city-mod
5: https://www.curseforge.com/minecraft/mc-mods/fexcraft-common-library

**Comment by Titoo8899** [comment]
The First is for Fishing a cool mod, the ElytraBombing is cool for make is possible to fall tnt with a flint and steel and the tnt was active and explode by a cooltime of 5 seconds the CDM is a Decorations mod and the FCL Mod is the core mod for CDM

**Comment by Titoo8899** [comment]
I have testet only with your mod and the same think was the fall then I this testet

**Comment by SuperMartijn642** [comment]
Seems it is once again a 1.12-only thing. Should be fixed now in Moving Elevators 1.3.2a for Minecraft 1.12.

Thank you for reporting the issue!
