### ISSUE TITLE
[Feature] Add compatibility with Redstone Pen mod

### ISSUE THREAD

**Issue by rabrunos** [SuperMartijn642/MovingElevators#98]
**Incompatibility with Redstone Pen mod**
Could add compatibility for [Redstone Pen](https://www.curseforge.com/minecraft/mc-mods/redstone-pen) mod

When redstone dust from the Redstone Pen mod is added to a block that belongs to the elevator, the elevator simply does not go up.
![minecraft](https://user-images.githubusercontent.com/83606488/154817621-ad795a49-8aa6-4271-bf43-611c90c426c2.gif)

**A doubt**
And on the cue, I'd also like to know why the lights don't stay on when the elevator moves.

**Comment by SuperMartijn642** [comment]
I assume that redstone dust from the Redstone Pen mod uses a block entity then. Block Entities cannot be part of the elevator cabin, thus the cabin won't move if you place it.
You can, however, just use vanilla redstone dust.

>I'd also like to know why the lights don't stay on when the elevator moves.

Minecraft's lighting works by having a light value for each block. When the elevator starts moving, the cabin blocks get removed, once the elevator arrives, the cabin blocks get placed again. Thus when the elevator is moving there are no blocks to emit light. Nothing I can do about this, Minecraft simply doesn't have any form of dynamic lighting.

**Comment by rabrunos** [comment]
I get it clearly! 
Thank you. 

I'll see if the developer of the pen mod can do something about it!
I don't want to use vanilla Redstone powder because it can't put on the ceiling or walls!

The redstone powder of the mod can be placed in these places. 
With this I can put the Redstone powder of the mod under neath the elevator cabin to create a system to open the doors automatically without being visually invasive or having to create blocks and blocks for a simple command open door to all floors.
